// Generated by gemini, prompt in readme under stage 4

using Microsoft.VisualStudio.TestTools.UnitTesting;
using Helpers;
using BlApi;
using BO;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;

namespace BlUnitTests;


/// <summary>
/// Unit tests for Courier logic in the Business Layer.
/// </summary>
[TestClass]
public class CourierTests
{
    private readonly IBl _bl = Factory.Get();


    /// <summary>
    /// Initializes the test environment before each test run.
    /// </summary>
    [TestInitialize]
    public void TestInitialize()
    {
        var dal = DalApi.Factory.Get;
        // 1. Wipe everything
        dal.ResetDB();
        Tools.ClearCaches();
        Tools.SeedCoordinateCache();

        // 2. Add required test IDs DIRECTLY to DAL (bypasses BL validation triggers)
        
        int[] idsToEnsure = { 123454321, 987654567, 111222333 };

        foreach (var id in idsToEnsure)
        {
            dal.Courier.Create(new DO.Courier(
                Id: id,
                FullName: "Test Courier",
                MobilePhone: "0551111111",
                Email: $"test{id}@example.com",
                Password: "password",
                Active: true,
                DeliveryType: DO.DeliveryTypes.Car,
                EmploymentStartTime: DateTime.Now.AddDays(-1),
                PersonalMaxDeliveryDistance: 10.0 // Valid distance
            ));
        }

        // 3. Now run seed logic. Wrap in try-catch so messy seed data 
        // doesn't kill the entire test suite.
        try
        {
            AdminManager.InitializeDB();
        }
        catch (Exception ex)
        {
            Trace.WriteLine($"Note: InitializeDB seed validation skipped: {ex.Message}");
        }
    }
    #region Create Tests

    /// <summary>
    /// Tests successful creation of a courier.
    /// </summary>
    [TestMethod]
    public void Test_CreateCourier_Success()
    {
        // Arrange
        var newCourier = new Courier
        {
            Id = 111222333,
            FullName = "New Courier",
            MobilePhone = "0551111111",
            Email = "new@courier.com",
            Password = "securepassword",
            Active = true,
            DeliveryType = DeliveryTypes.Car,
            EmploymentStartTime = _bl.Admin.GetClock(),
            PersonalMaxDeliveryDistance = 50
        };

        // Act
        _bl.Courier.Create(newCourier);
        var createdCourier = _bl.Courier.Read(newCourier.Id);

        // Assert
        Assert.IsNotNull(createdCourier);
        Assert.AreEqual("New Courier", createdCourier.FullName);
    }

    /// <summary>
    /// Tests that creating a courier with an existing ID throws an exception.
    /// </summary>
    [TestMethod]
    [ExpectedException(typeof(BlAlreadyExistsException))]
    public void Test_CreateCourier_AlreadyExists_ThrowsException()
    {
        // Arrange
        var existingCourier = _bl.Courier.ReadAll().First();
        var newCourierWithSameId = new Courier
        {
            Id = existingCourier.Id,
            FullName = "Duplicate Courier",
            MobilePhone = "0552222222",
            Email = "duplicate@courier.com",
            Password = "password",
            Active = true,
            DeliveryType = DeliveryTypes.OnFoot,
            EmploymentStartTime = _bl.Admin.GetClock()
        };

        // Act
        _bl.Courier.Create(newCourierWithSameId);
    }

    /// <summary>
    /// Tests that creating a courier with invalid data throws an exception.
    /// </summary>
    [TestMethod]
    [ExpectedException(typeof(BlInvalidInputException))]
    public void Test_CreateCourier_InvalidData_ThrowsException()
    {
        // Arrange
        var invalidCourier = new Courier
        {
            Id = 999888777,
            FullName = "", // Invalid
            MobilePhone = "0553333333",
            Email = "invalid@courier.com",
            Password = "password",
            Active = true,
            DeliveryType = DeliveryTypes.Bicycle,
            EmploymentStartTime = _bl.Admin.GetClock()
        };

        // Act
        _bl.Courier.Create(invalidCourier);
    }

    /// <summary>
    /// Tests that creating a courier with negative distance throws an exception.
    /// </summary>
    [TestMethod]
    [ExpectedException(typeof(BlInvalidInputException))]
    public void Test_CreateCourier_NegativeDistance_ThrowsException()
    {
        // Arrange
        var invalidCourier = new Courier
        {
            Id = 123123123,
            FullName = "Negative Distance",
            MobilePhone = "0500000000",
            Email = "neg@dist.com",
            Password = "pass",
            Active = true,
            DeliveryType = DeliveryTypes.Car,
            EmploymentStartTime = _bl.Admin.GetClock(),
            PersonalMaxDeliveryDistance = -5
        };

        // Act
        _bl.Courier.Create(invalidCourier);
    }

    #endregion

    #region Read Tests

    /// <summary>
    /// Tests successful reading of a courier by ID.
    /// </summary>
    [TestMethod]
    public void Test_ReadCourier_Success()
    {
        // Arrange
        var courierToRead = _bl.Courier.ReadAll().First();

        // Act
        var readCourier = _bl.Courier.Read(courierToRead.Id);

        // Assert
        Assert.IsNotNull(readCourier);
        Assert.AreEqual(courierToRead.Id, readCourier.Id);
    }

    /// <summary>
    /// Tests that reading a non-existent courier throws an exception.
    /// </summary>
    [TestMethod]
    [ExpectedException(typeof(BlDoesNotExistException))]
    public void Test_ReadCourier_NotFound_ThrowsException()
    {
        // Act
        _bl.Courier.Read(12345); // Non-existent ID
    }

    /// <summary>
    /// Tests that reading all couriers returns a list.
    /// </summary>
    [TestMethod]
    public void Test_ReadAllCouriers_ReturnsData()
    {
        // Act
        var couriers = _bl.Courier.ReadAll();

        // Assert
        Assert.IsTrue(couriers.Any(), "ReadAll should return a list of couriers.");
    }

    /// <summary>
    /// Tests that reading all couriers with a filter returns filtered data.
    /// </summary>
    [TestMethod]
    public void Test_ReadAllCouriers_WithFilter_ReturnsFilteredData()
    {
        // Arrange
        var allCouriers = _bl.Courier.ReadAll();
        
        // Act
        var activeCouriers = _bl.Courier.ReadAll(c => c.Active);

        // Assert
        Assert.IsTrue(activeCouriers.All(c => c.Active));
        if (allCouriers.Any(c => !c.Active))
            Assert.IsTrue(activeCouriers.Count() < allCouriers.Count());
    }

    #endregion

    #region Update Tests

    /// <summary>
    /// Tests successful update of a courier.
    /// </summary>
    [TestMethod]
    public void Test_UpdateCourier_Success()
    {
        // Arrange
        var courierToUpdate = _bl.Courier.Read(_bl.Courier.ReadAll().First().Id);
        courierToUpdate.FullName = "Updated Name";
        courierToUpdate.Email = "updated@email.com";

        // Act
        _bl.Courier.Update(courierToUpdate);
        var updatedCourier = _bl.Courier.Read(courierToUpdate.Id);

        // Assert
        Assert.AreEqual("Updated Name", updatedCourier.FullName);
        Assert.AreEqual("updated@email.com", updatedCourier.Email);
    }
    
    /// <summary>
    /// Tests successful update of courier's own details.
    /// </summary>
    [TestMethod]
    public void Test_UpdateMyDetails_Success()
    {
        // Arrange
        var courierToUpdate = _bl.Courier.Read(_bl.Courier.ReadAll().First().Id);
        
        // Act
        _bl.Courier.UpdateMyDetails(courierToUpdate.Id, fullName: "My New Name", phoneNum: "0509876543");
        var updatedCourier = _bl.Courier.Read(courierToUpdate.Id);

        // Assert
        Assert.AreEqual("My New Name", updatedCourier.FullName);
        Assert.AreEqual("0509876543", updatedCourier.MobilePhone);
    }

    /// <summary>
    /// Tests that updating a courier with invalid data throws an exception.
    /// </summary>
    [TestMethod]
    [ExpectedException(typeof(BlInvalidInputException))]
    public void Test_UpdateCourier_InvalidData_ThrowsException()
    {
        // Arrange
        var courierToUpdate = _bl.Courier.Read(_bl.Courier.ReadAll().First().Id);
        courierToUpdate.FullName = ""; // Invalid

        // Act
        _bl.Courier.Update(courierToUpdate);
    }

    /// <summary>
    /// Tests that updating a non-existent courier throws an exception.
    /// </summary>
    [TestMethod]
    [ExpectedException(typeof(BlDoesNotExistException))]
    public void Test_UpdateCourier_NotFound_ThrowsException()
    {
        // Arrange
        var nonExistentCourier = new Courier { Id = 12345, FullName = "Ghost" };

        // Act
        _bl.Courier.Update(nonExistentCourier);
    }

    #endregion

    #region Delete Tests

    /// <summary>
    /// Tests successful deletion of a courier.
    /// </summary>
    [TestMethod]
    public void Test_DeleteCourier_Success()
    {
        // Arrange
        var courierToDelete = _bl.Courier.ReadAll().First();
        
        // Act
        _bl.Courier.Delete(courierToDelete.Id);

        // Assert
        Assert.ThrowsException<BlDoesNotExistException>(() => _bl.Courier.Read(courierToDelete.Id));
    }

    /// <summary>
    /// Tests that deleting a non-existent courier throws an exception.
    /// </summary>
    [TestMethod]
    [ExpectedException(typeof(BlDoesNotExistException))]
    public void Test_DeleteCourier_NotFound_ThrowsException()
    {
        // Act
        _bl.Courier.Delete(12345); // Non-existent ID
    }

    #endregion

    #region Specific Logic Tests

    /// <summary>
    /// Tests that courier delivery history is returned correctly.
    /// </summary>
    [TestMethod]
    public void Test_GetCourierDeliveryHistory_ReturnsHistory()
    {
        // This is a complex test that requires creating orders and deliveries.
        // For a true unit test, this would involve mocking the Dal layer.
        // In this integration-style test, we rely on the DB being initialized.

        // Arrange: Find a courier and check they have history (the init DB should provide this)
        var courier = _bl.Courier.ReadAll().First(c => _bl.Courier.GetCourierDeliveryHistory(c.Id).Any());
        Debug.WriteLine($"Testing with history 1 Courier ID: {courier.Id}");

        // Act
        var history = _bl.Courier.GetCourierDeliveryHistory(courier.Id);

        // Assert
        Assert.IsTrue(history.Any());
        Assert.IsTrue(history.All(d => d.CourierId == courier.Id));
    }

    /// <summary>
    /// Tests that courier statistics are calculated correctly.
    /// </summary>
    [TestMethod]
    public void Test_GetCourierStatistics_CalculatesCorrectly()
    {
        // Arrange: Specifically find a courier with at least one COMPLETED delivery
        var courier = _bl.Courier.ReadAll()
            .FirstOrDefault(c => _bl.Courier.GetCourierDeliveryHistory(c.Id)
            .Any(d => d.DeliveryEndTime != null));

        // Safety check in case the seed data has no completed deliveries
        Assert.IsNotNull(courier, "No courier with completed deliveries found in seed data.");

        Debug.WriteLine($"Testing with history 2 Courier ID: {courier.Id}");

        // Act
        var stats = _bl.Courier.GetCourierStatistics(courier.Id);

        // Assert
        Assert.IsTrue(stats.TotalDeliveries > 0);
        Assert.IsTrue(stats.SuccessRate > 0);
    }

    /// <summary>
    /// Tests that open orders are returned for a courier with a max distance.
    /// </summary>
    [TestMethod]
    public void Test_GetOpenOrders_ReturnsAvailableOrders()
    {
        // Arrange: Find a courier, ensure they have a max distance set.
        var courier = _bl.Courier.Read(_bl.Courier.ReadAll().First().Id);
        courier.PersonalMaxDeliveryDistance = 1000; // Set a large distance
        _bl.Courier.Update(courier);

        // Act
        var openOrders = _bl.Courier.GetOpenOrders(courier.Id);

        // Assert
        Assert.IsTrue(openOrders.Any(), "With a large max distance, courier should see open orders from init data.");
        Assert.IsTrue(openOrders.All(o => o.OrderStatus == OrderStatus.Open));
    }

    /// <summary>
    /// Tests that all open orders are returned for a courier with no max distance.
    /// </summary>
    [TestMethod]
    public void Test_GetOpenOrders_NoDistanceSet_ReturnsAll()
    {
        // Arrange: Find a courier and ensure they have no max distance.
        var courier = _bl.Courier.Read(_bl.Courier.ReadAll().First().Id);
        courier.PersonalMaxDeliveryDistance = null;
        _bl.Courier.Update(courier);
        
        // Act
        var openOrders = _bl.Courier.GetOpenOrders(courier.Id);
        var allOrders = _bl.Order.ReadAll(o => o.OrderStatus == OrderStatus.Open);
        bool same =
        _bl.Courier.GetOpenOrders(courier.Id)
        .Select(c => c.Id)
        .ToHashSet()
        .SetEquals(
            allOrders
                .Select(c => c.Id)
        );

        // Assert
        Assert.IsTrue(same, "Courier with no max distance should see all open orders.");
    }

    /// <summary>
    /// Tests the logic for checking if an order is within a courier's range.
    /// </summary>
    [TestMethod]
    public void Test_IsOrderInCourierRange_Logic()
    {
        var dal = DalApi.Factory.Get;
        // Arrange
        var config = dal.Config;
        double lat = (double)config.Latitude!;
        double lon = (double)config.Longitude!;
        
        var courier = new Courier { PersonalMaxDeliveryDistance = 10 }; // 10 km
        
        // Create order ~0.5km away (0.005 deg lat is approx 0.55km)
        var orderNear = new Order { FullOrderAddress = "Ben Yehuda Street, Jerusalem" }; 
        
        // Create order ~110km away (1.0 deg lat is approx 111km)
        var orderFar = new Order { FullOrderAddress = "Test Far Address" };

        // Act & Assert
        Assert.IsTrue(CourierManager.IsOrderInCourierRange(orderNear, courier, lat, lon), "Order within distance should be allowed.");
        Assert.IsFalse(CourierManager.IsOrderInCourierRange(orderFar, courier, lat, lon), "Order beyond distance should be rejected.");
    }

    /// <summary>
    /// Tests that a courier becomes inactive after the inactivity range.
    /// </summary>
    [TestMethod]
    public void Test_CourierBecomesInactive_AfterInactivityRange()
    {
        // Arrange
        var config = _bl.Admin.GetConfig();
        var inactivityRange = config.InactivityRange;
        int testId = 999111999; // Unique ID for this test

        // Create a NEW active courier right now
        _bl.Courier.Create(new Courier
        {
            Id = testId,
            FullName = "Fresh Courier",
            MobilePhone = "0559999999",
            Email = "fresh@test.com",
            Password = "password",
            Active = true,
            DeliveryType = DeliveryTypes.Car,
            EmploymentStartTime = _bl.Admin.GetClock(), // Current clock time
            PersonalMaxDeliveryDistance = 10.0
        });

        var initialBoCourier = _bl.Courier.Read(testId);
        Assert.IsTrue(initialBoCourier.Active, "Courier must start as active.");

        // Act
        // Forward the clock past the threshold relative to the creation time
        _bl.Admin.ForwardClock(inactivityRange.Add(TimeSpan.FromMinutes(5)));

        // Read the courier - this triggers the deactivation check
        var updatedBoCourier = _bl.Courier.Read(testId);

        // Assert
        Assert.IsNotNull(updatedBoCourier, "Courier should still exist.");
        Assert.IsFalse(updatedBoCourier.Active, "Courier should have been deactivated.");
    }

    #endregion
}
