// Generated by gemini, prompt in readme under stage 4

using BlApi;
using BO;
using DalApi;
using Helpers;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Linq;

namespace BlUnitTests;

[TestClass]
public class OrderTests
{
    private readonly IBl _bl = BlApi.Factory.Get();
    private const int TEST_COURIER_ID = 888888888;

    [TestInitialize]
    public void TestInitialize()
    {
        var s_dal = DalApi.Factory.Get;

        // Full Reset to avoid seeded data problems
        s_dal.ResetDB();
        Tools.ClearCaches();
        Tools.SeedCoordinateCache();
        s_dal.Config.AdminId = 999999999;
        // Example company coordinates - change as appropriate for your tests
        s_dal.Config.CompanyFullAddress = "Hebron Road (central)";
        s_dal.Config.Latitude = 31.766509;
        s_dal.Config.Longitude = 35.225938;

        // reasonable urban speed assumptions
        s_dal.Config.AvgCarSpeedKmh = 40.0;
        s_dal.Config.AvgMotorcycleSpeedKmh = 35.0;
        s_dal.Config.AvgBicycleSpeedKmh = 15.0;
        s_dal.Config.AvgWalkingSpeedKmh = 5.0;

        // Delivery limits & thresholds
        s_dal.Config.MaxGeneralDeliveryDistanceKm = 10.0; // global max radius
        s_dal.Config.MaxDeliveryTimeSpan = TimeSpan.FromHours(2);
        s_dal.Config.RiskRange = TimeSpan.FromMinutes(10);
        s_dal.Config.InactivityRange = TimeSpan.FromMinutes(30);

        // set test clock to now (or any fixed time)
        s_dal.Config.Clock = DateTime.Now;

        // Create a stable courier for testing lifecycle methods
        s_dal.Courier.Create(new DO.Courier(
            Id: TEST_COURIER_ID,
            FullName: "Order System Tester",
            MobilePhone: "0557776666",
            Email: "order_tester@test.com",
            Password: "password",
            Active: true,
            DeliveryType: DO.DeliveryTypes.Car,
            EmploymentStartTime: _bl.Admin.GetClock(),
            PersonalMaxDeliveryDistance: 5000.0
        ));
    }

    #region Create & Validation Tests

    [TestMethod]
    public void Test_CreateOrder_Success()
    {
        var name = "Unique Create Successful";
        var newOrder = CreateValidTestOrder(name);
        _bl.Order.Create(newOrder);

        var created = _bl.Order.ReadAll().FirstOrDefault(o => o.CustomerFullName == name);
        Assert.IsNotNull(created);
        Assert.AreEqual(OrderStatus.Open, created.OrderStatus);
    }

    [TestMethod]
    public void Test_CreateOrder_ExceedsMaxGeneralDistance_Throws()
    {
        var config = _bl.Admin.GetConfig();
        config.MaxGeneralDeliveryDistanceKm = 1; // Strict limit
        _bl.Admin.SetConfig(config);

        var farOrder = CreateValidTestOrder("Far Away Customer");
        // Ben Yehuda Street is ~2.5km away, exceeding 1km limit

        Assert.ThrowsException<BlInvalidInputException>(() => _bl.Order.Create(farOrder));
    }

    [TestMethod]
    public void Test_CreateOrder_InvalidPhone_Throws()
    {
        var order = CreateValidTestOrder("Bad Phone");
        order.CustomerMobile = "123"; // Invalid format
        Assert.ThrowsException<BlInvalidInputException>(() => _bl.Order.Create(order));
    }

    #endregion

    #region Update & Delete Constraint Tests

    [TestMethod]
    public void Test_UpdateOrder_ImmutableFields_Preserved()
    {
        var originalName = "Original Name";
        var order = CreateAndGetOrder(originalName);
        var originalTime = order.OrderOpenTime;

        order.CustomerFullName = "New Name";
        _bl.Order.Update(order);

        var updated = _bl.Order.Read(order.Id);
        Assert.AreEqual(originalTime, updated.OrderOpenTime, "OrderOpenTime must be immutable during update.");
    }

    [TestMethod]
    public void Test_UpdateOrder_InProgress_Throws()
    {
        var order = CreateAndGetOrder("InProgress Update");
        _bl.Delivery.PickUp(TEST_COURIER_ID, order.Id);

        Assert.ThrowsException<BlDeliveryInProgressException>(() => _bl.Order.Update(order));
    }

    [TestMethod]
    public void Test_Delete_AssignedOrder_Throws()
    {
        var order = CreateAndGetOrder("Delete Assigned");
        _bl.Delivery.PickUp(TEST_COURIER_ID, order.Id);

        Assert.ThrowsException<BlOrderAlreadyAssignedException>(() => _bl.Order.Delete(order.Id));
    }

    #endregion

    #region Lifecycle & Tracking Tests

    [TestMethod]
    public void Test_OrderLifecycle_StatusTransitions()
    {
        var order = CreateAndGetOrder("Lifecycle Tester");
        Assert.AreEqual(OrderStatus.Open, order.OrderStatus);

        _bl.Delivery.PickUp(TEST_COURIER_ID, order.Id);
        Assert.AreEqual(OrderStatus.InProgress, _bl.Order.Read(order.Id).OrderStatus);

        _bl.Delivery.Deliver(TEST_COURIER_ID, DeliveryEndTypes.Delivered);
        Assert.AreEqual(OrderStatus.Delivered, _bl.Order.Read(order.Id).OrderStatus);
    }

    [TestMethod]
    public void Test_GetOrderTracking_DetailsCorrect()
    {
        var order = CreateAndGetOrder("Tracking Detail");
        _bl.Delivery.PickUp(TEST_COURIER_ID, order.Id);

        var tracking = _bl.Order.GetOrderTracking(order.Id);
        Assert.AreEqual(TEST_COURIER_ID, tracking.AssignedCourier.Id);
        Assert.IsNotNull(tracking.ExpectedDeliveryTime);
    }

    #endregion

    #region Timing & Schedule Status

    [TestMethod]
    public void Test_ScheduleStatus_ChangesOverTime()
    {
        var config = _bl.Admin.GetConfig();
        var order = CreateAndGetOrder("Timing Flow Target");

        _bl.Delivery.PickUp(TEST_COURIER_ID, order.Id);
        var track = _bl.Order.GetOrderTracking(order.Id);

        // Assert Initially OnTime
        Assert.AreEqual(ScheduleStatus.OnTime, track.DeliveryHistory.First().ScheduleStatus);

        // Move to Risk window (Remaining time < RiskRange)
        var timeToRisk = (DateTime)track.MaxDeliveryTime - _bl.Admin.GetClock() - config.RiskRange;
        _bl.Admin.ForwardClock(timeToRisk.Add(TimeSpan.FromSeconds(30)));

        Assert.AreEqual(ScheduleStatus.AtRisk, _bl.Order.GetOrderTracking(order.Id).DeliveryHistory.First().ScheduleStatus);

        // Move past deadline
        _bl.Admin.ForwardClock(config.RiskRange.Add(TimeSpan.FromMinutes(5)));
        Assert.AreEqual(ScheduleStatus.Late, _bl.Order.GetOrderTracking(order.Id).DeliveryHistory.First().ScheduleStatus);
    }

    #endregion

    #region Helpers
    private Order CreateValidTestOrder(string customerName)
    {
        return new Order
        {
            CustomerFullName = customerName,
            CustomerMobile = "0501112222",
            FullOrderAddress = "Ben Yehuda Street, Jerusalem",
            OrderType = OrderTypes.Pizza,
            VerbalDescription = "Hardened test order",
            Weight = 5,
            Volume = 2,
            Height = 10,
            Width = 10,
            OrderOpenTime = _bl.Admin.GetClock()
        };
    }

    private Order CreateAndGetOrder(string customerName)
    {
        var newOrder = CreateValidTestOrder(customerName);
        _bl.Order.Create(newOrder);
        return OrderManager.ReadAll().First(o => o.CustomerFullName == newOrder.CustomerFullName);
    }
    #endregion
}