﻿﻿﻿﻿﻿﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System;
using System.Globalization;
using System.Windows;
using System.Windows.Data;

namespace PL;

// IValueConverter is the interface required by WPF for data binding conversions.
// It requires two methods: Convert (Source -> UI) and ConvertBack (UI -> Source).

/// <summary>
/// Converts an Entity ID to a boolean for IsReadOnly property.
/// Returns true (ReadOnly) if ID != 0 (Update mode).
/// Returns false (Editable) if ID == 0 (Add mode).
/// </summary>
public class IdToReadOnlyConverter : IValueConverter
{
    // Called when updating the UI from the code property
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value is int id && id != 0)
            return true;
        return false;
    }

    // Called when updating the code property from the UI (rarely used for OneWay bindings)
    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) => throw new NotImplementedException();
}

/// <summary>
/// Converts an Entity ID to Visibility.
/// Returns Visible if ID != 0 (Update mode).
/// Returns Collapsed if ID == 0 (Add mode).
/// </summary>
public class IdToVisibilityConverter : IValueConverter
{
    // Returns Visibility.Visible or Visibility.Collapsed based on the ID value
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture) =>
        (value is int id && id != 0) ? Visibility.Visible : Visibility.Collapsed;

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) => throw new NotImplementedException();
}

/// <summary>
/// Converts a nullable double to string and back.
/// </summary>
public class NullableDoubleConverter : IValueConverter
{
    // Converts double? to string for the TextBox
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value == null) return "N/A";
        if (value is double d) return d.ToString(CultureInfo.InvariantCulture);
        if (value is double?) return (value as double?)?.ToString(CultureInfo.InvariantCulture) ?? "N/A";
        return value.ToString();
    }

    // Converts string input from TextBox back to double?
    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        var s = value?.ToString();
        
        if (string.IsNullOrWhiteSpace(s) || s.Equals("N/A", StringComparison.OrdinalIgnoreCase) || s.Equals("null", StringComparison.OrdinalIgnoreCase))
        {
            // If the target is a nullable double, return null (valid "empty")
            if (targetType == typeof(double?)) return null;
            // If the target is a regular double, return UnsetValue to ignore
            return DependencyProperty.UnsetValue;
        }

        if (double.TryParse(s, NumberStyles.Any, CultureInfo.InvariantCulture, out var d)) return d;
        
        // For invalid input (e.g. "abc"), return UnsetValue to ignore
        return DependencyProperty.UnsetValue; 
    }
}

// Handles formatting DateTime objects for display
public class DateTimeToStringConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture) =>
        value is DateTime dt ? dt.ToString("yyyy-MM-dd HH:mm:ss") : "N/A";

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        var s = value?.ToString();
        if (string.IsNullOrWhiteSpace(s) || s.Equals("N/A", StringComparison.OrdinalIgnoreCase))
        {
            return targetType == typeof(DateTime?) ? null : DependencyProperty.UnsetValue;
        }
        return DateTime.TryParse(s, out var dt) ? dt : DependencyProperty.UnsetValue;
    }
}

// Handles formatting TimeSpan objects for display
public class TimeSpanToStringConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture) =>
        value is TimeSpan ts ? ts.ToString() : "N/A";

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        var s = value?.ToString();
        if (string.IsNullOrWhiteSpace(s) || s.Equals("N/A", StringComparison.OrdinalIgnoreCase))
        {
            return targetType == typeof(TimeSpan?) ? null : DependencyProperty.UnsetValue;
        }
        return TimeSpan.TryParse(s, out var ts) ? ts : DependencyProperty.UnsetValue;
    }
}

// Safe conversion between String (TextBox) and Int (Code) to prevent crashes on empty input
public class StringToIntConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture) =>
        value?.ToString() ?? string.Empty;

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        var s = value?.ToString();
        if (string.IsNullOrWhiteSpace(s)) return 0;
        return int.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var result) ? result : DependencyProperty.UnsetValue;
    }
}

/// <summary>
/// Calculates the maximum delivery time based on the order's opening time and the configured max delivery duration.
/// </summary>
public class MaxDeliveryTimeConverter : IValueConverter
{
    // Calculates a value dynamically for display without storing it in the source object
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value is DateTime dt)
        {
            var bl = BlApi.Factory.Get();
            var maxTime = dt + bl.Admin.GetConfig().MaxDeliveryTimeSpan;
            return maxTime.ToString("dd/MM/yyyy HH:mm");
        }
        return "N/A";
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) => throw new NotImplementedException();
}

/// <summary>
/// Inverts a boolean value.
/// </summary>
public class InverseBooleanConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value is bool b) return !b;
        return true;
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) => throw new NotImplementedException();
}