﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System.Text;
using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

using System.ComponentModel;
using BlApi;
using BO;

namespace PL;

public partial class MainWindow : Window
{
    // BL is created lazily to prevent WPF designer crashes
    private static IBl? s_bl;

    #region Dependency Properties

    // Dependency Property for the simulated system time
    public DateTime CurrentTime
    {
        get => (DateTime)GetValue(CurrentTimeProperty);
        set => SetValue(CurrentTimeProperty, value);
    }

    public static readonly DependencyProperty CurrentTimeProperty =
        DependencyProperty.Register(
            nameof(CurrentTime),
            typeof(DateTime),
            typeof(MainWindow));

    // Dependency Property for the system configuration object
    public BO.Config Configuration
    {
        get => (BO.Config)GetValue(ConfigurationProperty);
        set => SetValue(ConfigurationProperty, value);
    }

    public static readonly DependencyProperty ConfigurationProperty =
        DependencyProperty.Register(
            nameof(Configuration),
            typeof(BO.Config),
            typeof(MainWindow));

    #endregion

    /// <summary>
    /// Initializes the main window and registers event handlers.
    /// </summary>
    public MainWindow()
    {
        InitializeComponent();

        // Register lifecycle event handlers explicitly
        Loaded += MainWindow_Loaded;
        Closing += MainWindow_Closing;
    }

    #region Window Lifecycle

    /// <summary>
    /// Handles the window loaded event to initialize BL and observers.
    /// </summary>
    // Initialize BL and Observers when window loads
    private void MainWindow_Loaded(object sender, RoutedEventArgs e)
    {
        if (DesignerProperties.GetIsInDesignMode(this))
            return;

        try
        {
            s_bl ??= Factory.Get();

            // Register observers
            s_bl.Admin.AddClockObserver(ClockObserver);
            s_bl.Admin.AddConfigObserver(ConfigObserver);

            // Initialize bound properties
            CurrentTime = s_bl.Admin.GetClock();
            Configuration = s_bl.Admin.GetConfig();
        }
        catch (Exception)
        {
            MessageBox.Show(
                "Failed to initialize the management console.",
                "Initialization Error",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Handles the window closing event to cleanup observers.
    /// </summary>
    // Cleanup observers when window closes
    private void MainWindow_Closing(object? sender, CancelEventArgs e)
    {
        if (s_bl == null)
            return;

        try
        {
            s_bl.Admin.RemoveClockObserver(ClockObserver);
            s_bl.Admin.RemoveConfigObserver(ConfigObserver);
        }
        catch
        {
            // Suppress shutdown errors
        }
    }

    #endregion

    #region Observer Methods (6g)

    /// <summary>
    /// Observer callback for clock updates.
    /// </summary>
    // Updates CurrentTime when the BL clock changes
    private void ClockObserver()
    {
        Dispatcher.Invoke(() =>
            CurrentTime = s_bl!.Admin.GetClock());
    }

    /// <summary>
    /// Observer callback for configuration updates.
    /// </summary>
    // Updates Configuration when BL config changes
    private void ConfigObserver()
    {
        Dispatcher.Invoke(() =>
            Configuration = s_bl!.Admin.GetConfig());
    }

    #endregion

    #region Clock Controls

    /// <summary>
    /// Advances the clock by one minute.
    /// </summary>
    // Methods to advance the system clock by various intervals
    private void AdvanceMinute_Click(object sender, RoutedEventArgs e) =>
        AdvanceClock(TimeSpan.FromMinutes(1));

    /// <summary>
    /// Advances the clock by one hour.
    /// </summary>
    private void AdvanceHour_Click(object sender, RoutedEventArgs e) =>
        AdvanceClock(TimeSpan.FromHours(1));

    /// <summary>
    /// Advances the clock by one day.
    /// </summary>
    private void AdvanceDay_Click(object sender, RoutedEventArgs e) =>
        AdvanceClock(TimeSpan.FromDays(1));

    /// <summary>
    /// Advances the clock by one month (30 days).
    /// </summary>
    private void AdvanceMonth_Click(object sender, RoutedEventArgs e) =>
        AdvanceClock(TimeSpan.FromDays(30));

    /// <summary>
    /// Advances the clock by one year (365 days).
    /// </summary>
    private void AdvanceYear_Click(object sender, RoutedEventArgs e) =>
        AdvanceClock(TimeSpan.FromDays(365));

    /// <summary>
    /// Advances the system clock by the specified time span.
    /// </summary>
    private void AdvanceClock(TimeSpan span)
    {
        try
        {
            s_bl!.Admin.ForwardClock(span);
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                ex.Message,
                "Clock Error",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
        }
    }

    #endregion

    #region Configuration

    /// <summary>
    /// Saves the current configuration settings to the BL.
    /// </summary>
    // Saves the modified configuration back to the BL
    private void SaveConfiguration_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            s_bl!.Admin.SetConfig(Configuration);
            MessageBox.Show("Configuration saved successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
        }
        catch (BlInvalidInputException ex)
        {
            MessageBox.Show(ex.Message, "Invalid Input", MessageBoxButton.OK, MessageBoxImage.Warning);
        }
        catch (BlInvalidAddressException ex)
        {
            MessageBox.Show(ex.Message, "Invalid Address", MessageBoxButton.OK, MessageBoxImage.Warning);
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                $"Failed to save configuration changes. {ex.Message}",
                "Configuration Error",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
    }

    #endregion

    #region Database Management (6k)

    /// <summary>
    /// Initializes the database with seed data after confirmation.
    /// </summary>
    // Re-initializes the database with seed data
    private void InitializeDb_Click(object sender, RoutedEventArgs e)
    {
        if (MessageBox.Show(
                "Are you sure you want to initialize the database?",
                "Confirm Initialization",
                MessageBoxButton.YesNo,
                MessageBoxImage.Question) != MessageBoxResult.Yes)
            return;

        try
        {
            Mouse.OverrideCursor = Cursors.Wait;
            CloseAllSecondaryWindows();
            s_bl!.Admin.InitializeDB();
            MessageBox.Show("Database initialized successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                $"Database initialization failed. {ex.Message}",
                "Database Error",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
        finally
        {
            Mouse.OverrideCursor = null;
        }
    }

    /// <summary>
    /// Resets the database to an empty state after confirmation.
    /// </summary>
    // Resets the database to an empty state
    private void ResetDb_Click(object sender, RoutedEventArgs e)
    {
        if (MessageBox.Show(
                "Are you sure you want to reset the database?",
                "Confirm Reset",
                MessageBoxButton.YesNo,
                MessageBoxImage.Warning) != MessageBoxResult.Yes)
            return;

        try
        {
            Mouse.OverrideCursor = Cursors.Wait;
            CloseAllSecondaryWindows();
            s_bl!.Admin.ResetDB();
            MessageBox.Show("Database reset successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                $"Database reset failed. {ex.Message}",
                "Database Error",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
        finally
        {
            Mouse.OverrideCursor = null;
        }
    }

    /// <summary>
    /// Closes all windows except the main window.
    /// </summary>
    // Helper to close other windows during DB operations
    private static void CloseAllSecondaryWindows()
    {
        foreach (Window window in Application.Current.Windows)
        {
            if (window is not MainWindow)
                window.Close();
        }
    }

    #endregion

    #region Navigation Buttons (6j)

    /// <summary>
    /// Opens the Courier List window.
    /// </summary>
    // Open the Courier List Window
    private void OpenCourierList_Click(object sender, RoutedEventArgs e) =>
        new Courier.CourierListWindow().Show();

    /// <summary>
    /// Opens the Order List window.
    /// </summary>
    // Open the Order List Window
    private void OpenOrderList_Click(object sender, RoutedEventArgs e) =>
        new Order.OrderListWindow().Show();

    /// <summary>
    /// Opens the Delivery List window.
    /// </summary>
    // Open the Delivery List Window
    private void OpenDeliveryList_Click(object sender, RoutedEventArgs e) =>
        new Delivery.DeliveryListWindow().Show();

    #endregion
}