﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System.Text;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

using System.ComponentModel;
using BlApi;
using BO;

namespace PL;

public partial class MainWindow : Window
{
    // BL is created lazily to prevent WPF designer crashes
    private static IBl? s_bl;

    #region Dependency Properties

    // Dependency Properties are special properties in WPF that support Data Binding.
    // When the value changes, the UI is automatically notified to update.

    // Dependency Property for the simulated system time
    public DateTime CurrentTime
    {
        get => (DateTime)GetValue(CurrentTimeProperty);
        set => SetValue(CurrentTimeProperty, value);
    }

    // Registration of the Dependency Property. This links the property name to the class.
    public static readonly DependencyProperty CurrentTimeProperty =
        DependencyProperty.Register(
            nameof(CurrentTime),
            typeof(DateTime),
            typeof(MainWindow));

    // Dependency Property for the system configuration object
    public BO.Config Configuration
    {
        get => (BO.Config)GetValue(ConfigurationProperty);
        set => SetValue(ConfigurationProperty, value);
    }

    public static readonly DependencyProperty ConfigurationProperty =
        DependencyProperty.Register(
            nameof(Configuration),
            typeof(BO.Config),
            typeof(MainWindow));

    #endregion

    /// <summary>
    /// Initializes the main window and registers event handlers.
    /// </summary>
    public MainWindow()
    {
        InitializeComponent();

        // Register lifecycle event handlers explicitly
        Loaded += MainWindow_Loaded;
        Closing += MainWindow_Closing;
    }

    #region Window Lifecycle

    /// <summary>
    /// Handles the window loaded event to initialize BL and observers.
    /// </summary>
    // Initialize BL and Observers when window loads
    private void MainWindow_Loaded(object sender, RoutedEventArgs e)
    {
        if (DesignerProperties.GetIsInDesignMode(this))
            return;

        try
        {
            s_bl ??= Factory.Get();

            // Register observers
            s_bl.Admin.AddClockObserver(ClockObserver);
            s_bl.Admin.AddConfigObserver(ConfigObserver);

            // Initialize bound properties
            CurrentTime = s_bl.Admin.GetClock();
            Configuration = s_bl.Admin.GetConfig();
        }
        catch (Exception)
        {
            MessageBox.Show(
                this,
                "Failed to initialize the management console.",
                "Initialization Error",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Handles the window closing event to cleanup observers.
    /// </summary>
    // Cleanup observers when window closes
    private void MainWindow_Closing(object? sender, CancelEventArgs e)
    {
        if (s_bl == null)
            return;

        try
        {
            s_bl.Admin.RemoveClockObserver(ClockObserver);
            s_bl.Admin.RemoveConfigObserver(ConfigObserver);
        }
        catch
        {
            // Suppress shutdown errors
        }
    }

    #endregion

    #region Observer Methods (6g)

    /// <summary>
    /// Observer callback for clock updates.
    /// </summary>
    // Updates CurrentTime when the BL clock changes
    private void ClockObserver()
    // Dispatcher.Invoke is crucial here. The BL observer runs on a background thread,
    // but UI updates MUST happen on the main UI thread. Invoke marshals the call to the UI thread.
    {
        Dispatcher.Invoke(() =>
            CurrentTime = s_bl!.Admin.GetClock());
    }

    /// <summary>
    /// Observer callback for configuration updates.
    /// </summary>
    // Updates Configuration when BL config changes
    private void ConfigObserver()
    {
        Dispatcher.Invoke(() =>
            Configuration = s_bl!.Admin.GetConfig());
    }

    #endregion

    #region Clock Controls

    /// <summary>
    /// Advances the clock by one minute.
    /// </summary>
    // Methods to advance the system clock by various intervals
    private void AdvanceMinute_Click(object sender, RoutedEventArgs e) =>
        AdvanceClock(TimeSpan.FromMinutes(1));

    /// <summary>
    /// Advances the clock by one hour.
    /// </summary>
    private void AdvanceHour_Click(object sender, RoutedEventArgs e) =>
        AdvanceClock(TimeSpan.FromHours(1));

    /// <summary>
    /// Advances the clock by one day.
    /// </summary>
    private void AdvanceDay_Click(object sender, RoutedEventArgs e) =>
        AdvanceClock(TimeSpan.FromDays(1));

    /// <summary>
    /// Advances the clock by one month (30 days).
    /// </summary>
    private void AdvanceMonth_Click(object sender, RoutedEventArgs e) =>
        AdvanceClock(TimeSpan.FromDays(30));

    /// <summary>
    /// Advances the clock by one year (365 days).
    /// </summary>
    private void AdvanceYear_Click(object sender, RoutedEventArgs e) =>
        AdvanceClock(TimeSpan.FromDays(365));

    /// <summary>
    /// Advances the system clock by the specified time span.
    /// </summary>
    private void AdvanceClock(TimeSpan span)
    {
        try
        {
            s_bl!.Admin.ForwardClock(span);
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                this,
                ex.Message,
                "Clock Error",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
        }
    }

    #endregion

    #region Configuration

    /// <summary>
    /// Saves the current configuration settings to the BL.
    /// </summary>
    // Saves the modified configuration back to the BL
    private void SaveConfiguration_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            // 1. Capture the original state from BL to compare against.
            var originalConfig = s_bl!.Admin.GetConfig();
            
            // 2. Check for UI-level validation errors (e.g., format errors like "abc" in an int field).
            string uiErrors = Tools.GetUiValidationErrors(this);
            bool hasUiErrors = !string.IsNullOrEmpty(uiErrors);
            
            // 3. Check if the underlying object has actually changed compared to the original.
            bool hasValidChanges = Tools.IsInstanceChanged(originalConfig, Configuration);

            // Case A: UI has errors, but NO valid changes were made to other fields.
            // Action: Just show the error and revert the invalid UI input to match the source.
            if (hasUiErrors && !hasValidChanges)
            {
                MessageBox.Show(this, $"Invalid input:\n{uiErrors}", "Invalid Input", MessageBoxButton.OK, MessageBoxImage.Warning);
                var temp = Configuration;
                // Force a binding refresh by setting a distinct dummy value.
                Configuration = new BO.Config { MaxDeliveryTimeSpan = TimeSpan.MinValue };
                Configuration = temp;
                return;
            }

            // Case B: No UI errors and No valid changes.
            // Action: Inform user nothing happened.
            if (!hasUiErrors && !hasValidChanges)
            {
                MessageBox.Show(this, "No changes were made.", "Information", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            // Case C: Valid changes exist (possibly mixed with UI errors).
            // Action: Attempt to save the valid changes to the BL.
            s_bl!.Admin.SetConfig(Configuration);

            // If save was successful:
            if (hasUiErrors)
            {
                // Case C1: Partial Success (Valid saved, UI errors reverted).
                MessageBox.Show(this, $"Partial Success: Valid changes were saved.\n\nInvalid format inputs were reverted:\n{uiErrors}", "Partial Success", MessageBoxButton.OK, MessageBoxImage.Information);
                var temp = Configuration;
                Configuration = new BO.Config 
                { 
                    MaxDeliveryTimeSpan = TimeSpan.MinValue,
                    RiskRange = TimeSpan.MinValue,
                    InactivityRange = TimeSpan.MinValue
                };
                Configuration = temp;
            }
            else
            {
                // Case C2: Full Success.
                MessageBox.Show(this, "Configuration saved successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
            }
        }
        catch (BlInvalidInputException ex)
        {
            // Case D: BL Validation Failed.
            // Even if UI validation passed, the BL might reject values (e.g., negative numbers).

            // Capture UI errors if any existed before the save attempt
            string uiErrors = Tools.GetUiValidationErrors(this);
            bool hasUiErrors = !string.IsNullOrEmpty(uiErrors);
            StringBuilder msg = new StringBuilder();
            
            if (hasUiErrors)
                msg.AppendLine("Invalid format inputs:").AppendLine(uiErrors);
            
            // Revert invalid fields to original values based on BL exception details
            if (ex.ValidationErrors.Count > 0)
            {
                var original = s_bl!.Admin.GetConfig();
                Tools.RevertInvalidProperties(Configuration, original, ex.ValidationErrors);

                // Force UI refresh
                var temp = Configuration;
                Configuration = new BO.Config 
                { 
                    MaxDeliveryTimeSpan = TimeSpan.MinValue,
                    RiskRange = TimeSpan.MinValue,
                    InactivityRange = TimeSpan.MinValue
                };
                Configuration = temp;

                // Check if there are still valid changes remaining after reverting the invalid ones
                if (!Tools.IsInstanceChanged(original, Configuration))
                {
                    // Case D1: All changes were invalid.
                    MessageBox.Show(this, msg.Append(ex.Message).ToString(), "Invalid Input", MessageBoxButton.OK, MessageBoxImage.Warning);
                }
                else
                {
                    // Case D2: Partial Success (BL errors reverted, Valid changes remain).
                    // Retry saving the valid values
                    try
                    {
                        s_bl!.Admin.SetConfig(Configuration);
                        MessageBox.Show(this, $"Partial Success: Invalid values were reverted. Valid changes were saved.\n\nDetails:\n{msg}{ex.Message}", "Partial Success", MessageBoxButton.OK, MessageBoxImage.Information);
                    }
                    catch (Exception retryEx)
                    {
                        MessageBox.Show(this, $"Error saving configuration: {retryEx.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    }
                }
            }
            else
            {
                // General BL error not tied to specific fields
                MessageBox.Show(this, msg.Append(ex.Message).ToString(), "Invalid Input", MessageBoxButton.OK, MessageBoxImage.Warning);
            }
        }
        catch (BlInvalidAddressException ex)
        {
            MessageBox.Show(this, ex.Message, "Invalid Address", MessageBoxButton.OK, MessageBoxImage.Warning);
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                this,
                $"Failed to save configuration changes. {ex.Message}",
                "Configuration Error",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
    }

    #endregion

    #region Database Management (6k)

    /// <summary>
    /// Initializes the database with seed data after confirmation.
    /// </summary>
    // Re-initializes the database with seed data
    // 'async' keyword allows us to use 'await' inside the method to pause execution without freezing the UI.
    private async void InitializeDb_Click(object sender, RoutedEventArgs e)
    {
        if (MessageBox.Show(
                this,
                "Are you sure you want to initialize the database?",
                "Confirm Initialization",
                MessageBoxButton.YesNo,
                MessageBoxImage.Question) != MessageBoxResult.Yes)
            return;

        try
        {
            // Change cursor to hourglass to indicate work
            Mouse.OverrideCursor = Cursors.Wait;
            CloseAllSecondaryWindows();
            s_bl!.Admin.InitializeDB();

            // Force refresh of bound properties to reflect changes immediately
            CurrentTime = s_bl.Admin.GetClock();
            Configuration = new BO.Config 
            { 
                MaxDeliveryTimeSpan = TimeSpan.MinValue,
                RiskRange = TimeSpan.MinValue,
                InactivityRange = TimeSpan.MinValue
            };
            Configuration = s_bl.Admin.GetConfig();

            Mouse.OverrideCursor = null;

            // Allow UI to refresh and secondary windows to fully close before showing message
            // 'await Task.Delay' yields control back to the UI loop, letting it redraw/process events.
            await Task.Delay(200);
            MessageBox.Show(this, "Database initialized successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
        }
        catch (Exception ex)
        {
            Mouse.OverrideCursor = null;
            MessageBox.Show(
                this,
                $"Database initialization failed. {ex.Message}",
                "Database Error",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
        finally
        {
            Mouse.OverrideCursor = null;
        }
    }

    /// <summary>
    /// Resets the database to an empty state after confirmation.
    /// </summary>
    // Resets the database to an empty state
    private async void ResetDb_Click(object sender, RoutedEventArgs e)
    {
        if (MessageBox.Show(
                this,
                "Are you sure you want to reset the database?",
                "Confirm Reset",
                MessageBoxButton.YesNo,
                MessageBoxImage.Warning) != MessageBoxResult.Yes)
            return;

        try
        {
            Mouse.OverrideCursor = Cursors.Wait;
            CloseAllSecondaryWindows();
            s_bl!.Admin.ResetDB();

            // Force refresh of bound properties to reflect changes immediately
            CurrentTime = s_bl.Admin.GetClock();
            Configuration = new BO.Config 
            { 
                MaxDeliveryTimeSpan = TimeSpan.MinValue,
                RiskRange = TimeSpan.MinValue,
                InactivityRange = TimeSpan.MinValue
            };
            Configuration = s_bl.Admin.GetConfig();

            Mouse.OverrideCursor = null;

            // Allow UI to refresh and secondary windows to fully close before showing message
            await Task.Delay(200);
            MessageBox.Show(this, "Database reset successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
        }
        catch (Exception ex)
        {
            Mouse.OverrideCursor = null;
            MessageBox.Show(
                this,
                $"Database reset failed. {ex.Message}",
                "Database Error",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
        finally
        {
            Mouse.OverrideCursor = null;
        }
    }

    /// <summary>
    /// Closes all windows except the main window.
    /// </summary>
    // Helper to close other windows during DB operations
    private static void CloseAllSecondaryWindows()
    {
        Application.Current.Windows.Cast<Window>()
            .Where(window => window is not MainWindow)
            .ToList()
            .ForEach(window => window.Close());
    }

    #endregion

    #region Navigation Buttons (6j)

    /// <summary>
    /// Opens the Courier List window.
    /// </summary>
    // Open the Courier List Window
    private void OpenCourierList_Click(object sender, RoutedEventArgs e) =>
        Tools.OpenWindow(() => new Courier.CourierListWindow());

    /// <summary>
    /// Opens the Order List window.
    /// </summary>
    // Open the Order List Window
    private void OpenOrderList_Click(object sender, RoutedEventArgs e) =>
        Tools.OpenWindow(() => new Order.OrderListWindow());

    /// <summary>
    /// Opens the Delivery List window.
    /// </summary>
    // Open the Delivery List Window
    private void OpenDeliveryList_Click(object sender, RoutedEventArgs e) =>
        Tools.OpenWindow(() => new Delivery.DeliveryListWindow());

    #endregion
}