﻿﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
﻿using System;
using System.Linq;
using System.Windows;

namespace PL;

// Static helper class for common UI operations
internal static class Tools
{
    public static void ExecuteSafeAction(Window window, Action action, string successMessage = "")
    {
        try
        {
            action();
            if (!string.IsNullOrEmpty(successMessage))
            {
                MessageBox.Show(window, successMessage, "Success", MessageBoxButton.OK, MessageBoxImage.Information);
            }
            window.Close();
        }
        catch (Exception ex)
        {
            MessageBox.Show(window, ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Helper to open a window of a specific type.
    /// If a window of that type is already open, it can either be activated or replaced.
    /// </summary>
    /// <remarks>
    /// This prevents multiple instances of the same window (e.g., multiple Courier Lists) from cluttering the screen.
    /// </remarks>
    /// <typeparam name="T">The type of the window.</typeparam>
    /// <param name="creator">Function to create a new instance of the window.</param>
    /// <param name="predicate">Optional filter to find a specific instance of the window (e.g. by mode).</param>
    /// <param name="replace">If true, closes the existing window before opening a new one.</param>
    public static void OpenWindow<T>(Func<T>? creator = null, Func<T, bool>? predicate = null, bool replace = false) where T : Window
    {
        // Search existing windows in the application for type T
        var query = Application.Current.Windows.OfType<T>();
        if (predicate != null)
            query = query.Where(predicate);

        var window = query.FirstOrDefault();
        
        // If found, either replace it or bring it to front
        if (window != null)
        {
            if (replace)
            {
                window.Close();
                if (creator != null)
                {
                    var newWindow = creator();
                    newWindow.Show();
                    newWindow.Activate();
                }
            }
            else
            {
                window.Activate();
                if (window.WindowState == WindowState.Minimized)
                    window.WindowState = WindowState.Normal;
            }
        }
        else
        // If not found, create a new one
        {
            if (creator != null)
            {
                var newWindow = creator();
                newWindow.Show();
                newWindow.Activate();
            }
        }
    }
}