﻿﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System;
using System.Windows;
using BlApi;

namespace PL.Courier;

/// <summary>
/// Interaction logic for CourierWindow.xaml
/// </summary>
public partial class CourierWindow : Window
{
    // Access to the Business Layer via Factory
    private static IBl s_bl = Factory.Get();

    // The entity being edited/added. Bound to the UI.
    public BO.Courier CurrentCourier
    {
        get { return (BO.Courier)GetValue(CurrentCourierProperty); }
        set { SetValue(CurrentCourierProperty, value); }
    }

    // Dependency Property for the Courier entity being added or updated
    public static readonly DependencyProperty CurrentCourierProperty =
        DependencyProperty.Register("CurrentCourier", typeof(BO.Courier), typeof(CourierWindow), new PropertyMetadata(null));

    // Text for the action button ("Add" or "Update")
    public string ButtonText
    {
        get { return (string)GetValue(ButtonTextProperty); }
        set { SetValue(ButtonTextProperty, value); }
    }

    public static readonly DependencyProperty ButtonTextProperty =
        DependencyProperty.Register("ButtonText", typeof(string), typeof(CourierWindow), new PropertyMetadata("Add"));

    // Controls whether the ID field is editable (Editable only in Add mode)
    public bool IsIdReadOnly
    {
        get { return (bool)GetValue(IsIdReadOnlyProperty); }
        set { SetValue(IsIdReadOnlyProperty, value); }
    }

    public static readonly DependencyProperty IsIdReadOnlyProperty =
        DependencyProperty.Register("IsIdReadOnly", typeof(bool), typeof(CourierWindow), new PropertyMetadata(false));

    /// <summary>
    /// Constructor for CourierWindow.
    /// </summary>
    /// <param name="id">The ID of the courier to update, or 0 to add a new courier.</param>
    public CourierWindow(int id = 0)
    {
        ButtonText = id == 0 ? "Add" : "Update";
        InitializeComponent();
        Init(id);
    }

    /// <summary>
    /// Initializes the window state based on the mode (Add vs Update).
    /// </summary>
    private void Init(int id)
    {
        IsIdReadOnly = id != 0;
        // If ID is 0, we are in ADD mode. If ID != 0, we are in UPDATE mode.
        try
        {
            if (id == 0)
            {
                // Add Mode: Initialize with default values
                CurrentCourier = new BO.Courier
                {
                    Active = true,
                    EmploymentStartTime = s_bl.Admin.GetClock(),
                    DeliveryType = BO.DeliveryTypes.Motorcycle // Default
                };
            }
            else
            {
                // Update Mode: Load existing courier and register observer
                CurrentCourier = s_bl.Courier.Read(id);
                // Register for updates on this specific ID so the window updates if the courier changes elsewhere
                s_bl.Courier.AddObserver(id, Observer);
                s_bl.Admin.AddClockObserver(Observer);
                Closing += (s, e) =>
                {
                    s_bl.Courier.RemoveObserver(id, Observer);
                    s_bl.Admin.RemoveClockObserver(Observer);
                };
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            Close();
        }
    }

    /// <summary>
    /// Observer method to refresh the displayed courier data if it changes externally.
    /// </summary>
    private void Observer()
    {
        Dispatcher.Invoke(() =>
        // Re-read the entity from BL to refresh UI
        {
            if (CurrentCourier != null)
                CurrentCourier = s_bl.Courier.Read(CurrentCourier.Id);
        });
    }

    /// <summary>
    /// Handles the Add/Update button click.
    /// </summary>
    private void BtnAddUpdate_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            if (ButtonText == "Add")
                // Call Create in BL
                s_bl.Courier.Create(CurrentCourier);
            else
                s_bl.Courier.Update(CurrentCourier);

            MessageBox.Show(this, $"Courier {ButtonText}ed successfully!", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
            Close();
        }
        catch (BO.BlInvalidInputException ex)
        {
            MessageBox.Show(this, ex.Message, "Invalid Input", MessageBoxButton.OK, MessageBoxImage.Warning);
            
            // Revert invalid fields to original values if in Update mode
            // This resets the UI to the last valid state from the DB
            if (ButtonText == "Update" && ex.ValidationErrors.Count > 0)
            {
                var original = s_bl.Courier.Read(CurrentCourier.Id);
                foreach (var error in ex.ValidationErrors)
                {
                    var prop = typeof(BO.Courier).GetProperty(error.Key);
                    if (prop != null && prop.CanWrite)
                    {
                        prop.SetValue(CurrentCourier, prop.GetValue(original));
                    }
                }
                // Force UI refresh
                var temp = CurrentCourier;
                CurrentCourier = null;
                CurrentCourier = temp;
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }
}
