﻿﻿﻿﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System;
using System.Text;
using System.Windows;
using BlApi;
using PL;

namespace PL.Courier;

/// <summary>
/// Interaction logic for CourierWindow.xaml
/// </summary>
public partial class CourierWindow : Window
{
    // Access to the Business Layer via Factory
    private static IBl s_bl = Factory.Get();

    // The entity being edited/added. Bound to the UI.
    public BO.Courier CurrentCourier
    {
        get { return (BO.Courier)GetValue(CurrentCourierProperty); }
        set { SetValue(CurrentCourierProperty, value); }
    }

    // Dependency Property for the Courier entity being added or updated
    public static readonly DependencyProperty CurrentCourierProperty =
        DependencyProperty.Register("CurrentCourier", typeof(BO.Courier), typeof(CourierWindow), new PropertyMetadata(null));

    // Text for the action button ("Add" or "Update")
    public string ButtonText
    {
        get { return (string)GetValue(ButtonTextProperty); }
        set { SetValue(ButtonTextProperty, value); }
    }

    public static readonly DependencyProperty ButtonTextProperty =
        DependencyProperty.Register("ButtonText", typeof(string), typeof(CourierWindow), new PropertyMetadata("Add"));

    // Controls whether the ID field is editable (Editable only in Add mode)
    public bool IsIdReadOnly
    {
        get { return (bool)GetValue(IsIdReadOnlyProperty); }
        set { SetValue(IsIdReadOnlyProperty, value); }
    }

    public static readonly DependencyProperty IsIdReadOnlyProperty =
        DependencyProperty.Register("IsIdReadOnly", typeof(bool), typeof(CourierWindow), new PropertyMetadata(false));

    /// <summary>
    /// Constructor for CourierWindow.
    /// </summary>
    /// <param name="id">The ID of the courier to update, or 0 to add a new courier.</param>
    public CourierWindow(int id = 0)
    {
        ButtonText = id == 0 ? "Add" : "Update";
        InitializeComponent();
        Init(id);
    }

    /// <summary>
    /// Initializes the window state based on the mode (Add vs Update).
    /// </summary>
    private void Init(int id)
    {
        IsIdReadOnly = id != 0;
        // If ID is 0, we are in ADD mode. If ID != 0, we are in UPDATE mode.
        try
        {
            if (id == 0)
            {
                // Add Mode: Initialize with default values
                CurrentCourier = new BO.Courier
                {
                    Active = true,
                    EmploymentStartTime = s_bl.Admin.GetClock(),
                    DeliveryType = BO.DeliveryTypes.Motorcycle // Default
                };
            }
            else
            {
                // Update Mode: Load existing courier and register observer
                CurrentCourier = s_bl.Courier.Read(id);
                // Register for updates on this specific ID so the window updates if the courier changes elsewhere
                s_bl.Courier.AddObserver(id, Observer);
                s_bl.Admin.AddClockObserver(Observer);
                Closing += (s, e) =>
                {
                    s_bl.Courier.RemoveObserver(id, Observer);
                    s_bl.Admin.RemoveClockObserver(Observer);
                };
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            Close();
        }
    }

    /// <summary>
    /// Observer method to refresh the displayed courier data if it changes externally.
    /// </summary>
    private void Observer()
    {
        Dispatcher.Invoke(() =>
        // Re-read the entity from BL to refresh UI
        {
            if (CurrentCourier != null)
                CurrentCourier = s_bl.Courier.Read(CurrentCourier.Id);
        });
    }

    /// <summary>
    /// Handles the Add/Update button click.
    /// </summary>
    private void BtnAddUpdate_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            // Check for UI format errors (e.g. letters in numeric fields)
            string uiErrors = Tools.GetUiValidationErrors(this);
            bool hasUiErrors = !string.IsNullOrEmpty(uiErrors);

            if (ButtonText == "Update")
            {
                var original = s_bl.Courier.Read(CurrentCourier.Id);
                // Ignore calculated/readonly properties that might change due to time passing or BL logic
                bool hasValidChanges = Tools.IsInstanceChanged(original, CurrentCourier, nameof(BO.Courier.YearsEmployed), nameof(BO.Courier.IsInDelivery));

                // Case 1: No valid changes and no UI errors -> No op.
                if (!hasValidChanges && !hasUiErrors)
                {
                    MessageBox.Show(this, "No changes were made.", "Information", MessageBoxButton.OK, MessageBoxImage.Information);
                    Close();
                    return;
                }
                
                // Case 2: No valid changes but UI errors exist -> Show error and revert UI.
                if (!hasValidChanges && hasUiErrors)
                {
                    MessageBox.Show(this, $"Invalid input:\n{uiErrors}", "Invalid Input", MessageBoxButton.OK, MessageBoxImage.Warning);
                    var temp = CurrentCourier;
                    CurrentCourier = null;
                    CurrentCourier = temp; // Force binding refresh
                    return;
                }
            }

            // Attempt to save (Create or Update)
            if (ButtonText == "Add")
                // Call Create in BL
                s_bl.Courier.Create(CurrentCourier);
            else
                s_bl.Courier.Update(CurrentCourier);

            if (hasUiErrors)
            {
                // Case 4: Partial Success (Update Mode) - Valid changes saved, UI errors reverted.
                MessageBox.Show(this, $"Partial Success: Valid changes were saved.\n\nInvalid format inputs were reverted:\n{uiErrors}", "Partial Success", MessageBoxButton.OK, MessageBoxImage.Information);
                
                var temp = CurrentCourier;
                CurrentCourier = null;
                CurrentCourier = temp; // Force binding refresh
            }
            else
            {
                // Case 5: Full Success -> Close window.
                MessageBox.Show(this, $"Courier {(ButtonText == "Add" ? "Added" : "Updated")} successfully!", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
                Close();
            }
        }
        catch (BO.BlInvalidInputException ex)
        {
            // Case 6: BL Validation Failed (Logic errors).
            
            string uiErrors = Tools.GetUiValidationErrors(this);
            bool hasUiErrors = !string.IsNullOrEmpty(uiErrors);
            StringBuilder msg = new StringBuilder();
            if (hasUiErrors) msg.AppendLine("Invalid format inputs:").AppendLine(uiErrors);

            // Revert invalid fields to original values if in Update mode
            // This resets the UI to the last valid state from the DB
            if (ButtonText == "Update" && ex.ValidationErrors.Count > 0)
            {
                var original = s_bl.Courier.Read(CurrentCourier.Id);
                Tools.RevertInvalidProperties(CurrentCourier, original, ex.ValidationErrors);

                // Force UI refresh
                var temp = CurrentCourier;
                CurrentCourier = null;
                CurrentCourier = temp;

                // Retry saving valid changes
                if (Tools.IsInstanceChanged(original, CurrentCourier, nameof(BO.Courier.YearsEmployed), nameof(BO.Courier.IsInDelivery)))
                {
                    try
                    {
                        // Case 6a: Partial Success (BL errors reverted, valid changes saved).
                        s_bl.Courier.Update(CurrentCourier);
                        MessageBox.Show(this, $"Partial Success: Invalid values were reverted. Valid changes were saved.\n\nDetails:\n{msg}{ex.Message}", "Partial Success", MessageBoxButton.OK, MessageBoxImage.Information);
                        return;
                    }
                    catch (BO.BlDeliveryInProgressException deliveryEx)
                    {
                        // Handle mixed case: Invalid Input fixed, now hit Logic Error (Active/DeliveryType)
                        var freshOriginal = s_bl.Courier.Read(CurrentCourier.Id);
                        CurrentCourier.Active = freshOriginal.Active;
                        CurrentCourier.DeliveryType = freshOriginal.DeliveryType;
                        
                        var temp2 = CurrentCourier; CurrentCourier = null; CurrentCourier = temp2;

                        try 
                        {
                             s_bl.Courier.Update(CurrentCourier);
                             MessageBox.Show(this, $"Partial Success: Invalid values and Restricted fields were reverted. Valid changes were saved.\n\nDetails:\n{msg}{ex.Message}\n{deliveryEx.Message}", "Partial Success", MessageBoxButton.OK, MessageBoxImage.Information);
                             return;
                        }
                        catch (Exception retryEx)
                        {
                             msg.AppendLine($"Retry failed: {retryEx.Message}");
                        }
                    }
                    catch (Exception retryEx)
                    {
                        msg.AppendLine($"Retry failed: {retryEx.Message}");
                    }
                }
            }
            
            // Case 6b: Failure (Add Mode or Update Mode with no valid changes left).
            MessageBox.Show(this, msg.Append(ex.Message).ToString(), "Invalid Input", MessageBoxButton.OK, MessageBoxImage.Warning);
            if (hasUiErrors)
            {
                var temp = CurrentCourier;
                CurrentCourier = null;
                CurrentCourier = temp;
            }
        }
        catch (BO.BlDeliveryInProgressException ex)
        {
            // Handle logic errors for Active/DeliveryType similar to validation errors (Partial Success)
            // These properties cannot be changed while a delivery is in progress.
            if (ButtonText == "Update")
            {
                var original = s_bl.Courier.Read(CurrentCourier.Id);
                CurrentCourier.Active = original.Active;
                CurrentCourier.DeliveryType = original.DeliveryType;

                // Force UI refresh
                var temp = CurrentCourier;
                CurrentCourier = null;
                CurrentCourier = temp;

                // Retry saving valid changes (if any remain)
                if (Tools.IsInstanceChanged(original, CurrentCourier, nameof(BO.Courier.YearsEmployed), nameof(BO.Courier.IsInDelivery)))
                {
                    try
                    {
                        s_bl.Courier.Update(CurrentCourier);
                        MessageBox.Show(this, $"Partial Success: Invalid values (Active/DeliveryType) were reverted. Valid changes were saved.\n\nDetails:\n{ex.Message}", "Partial Success", MessageBoxButton.OK, MessageBoxImage.Information);
                        return;
                    }
                    catch (Exception retryEx)
                    {
                        // If retry fails, show error but keep valid changes in UI so user can try again
                        MessageBox.Show(this, $"Retry failed: {retryEx.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                        return; // Keep UI state (do not fall through to full revert)
                    }
                }
            }

            MessageBox.Show(this, ex.Message, "Operation Not Allowed", MessageBoxButton.OK, MessageBoxImage.Warning);
            // Revert to original state
            if (ButtonText == "Update") { try { CurrentCourier = s_bl.Courier.Read(CurrentCourier.Id); } catch { Close(); } }
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            // Revert to original state if update failed to ensure UI matches DB state
            if (ButtonText == "Update")
            {
                try
                {
                    CurrentCourier = s_bl.Courier.Read(CurrentCourier.Id);
                }
                catch
                {
                    Close(); // If entity no longer exists or read fails, close window
                }
            }
        }
    }
}
