﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace PL.Courier;

    /// <summary>
    /// Interaction logic for CourierListWindow.xaml
    /// </summary>
    public partial class CourierListWindow : Window
    {
        // Access to the Business Layer
        static readonly BlApi.IBl s_bl = BlApi.Factory.Get();

        // Using object to allow "None" (string) or Enum value
        public object StatusFilter { get; set; } = "None";

        // Dependency Property for the list of couriers bound to the DataGrid
        public IEnumerable<BO.CourierInList> CourierList
        {
            get { return (IEnumerable<BO.CourierInList>)GetValue(CourierListProperty); }
            set { SetValue(CourierListProperty, value); }
        }

        public static readonly DependencyProperty CourierListProperty =
            DependencyProperty.Register("CourierList", typeof(IEnumerable<BO.CourierInList>), typeof(CourierListWindow), new PropertyMetadata(null));

        // The currently selected courier in the DataGrid
        public BO.CourierInList? SelectedCourier
        {
            get { return (BO.CourierInList?)GetValue(SelectedCourierProperty); }
            set { SetValue(SelectedCourierProperty, value); }
        }

        public static readonly DependencyProperty SelectedCourierProperty =
            DependencyProperty.Register("SelectedCourier", typeof(BO.CourierInList), typeof(CourierListWindow), new PropertyMetadata(null));

        public CourierListWindow()
        {
            InitializeComponent();
        }

        /// <summary>
        /// Refreshes the courier list based on the selected filter.
        /// </summary>
        private void RefreshList()
        {
            CourierList = (StatusFilter is BO.DeliveryTypes type)
                ? s_bl.Courier.ReadAll(c => c.DeliveryType == type)
                : s_bl.Courier.ReadAll();
        }

        /// <summary>
        /// Event handler for filter selection change.
        /// </summary>
        private void cbStatusSelector_SelectionChanged(object sender, SelectionChangedEventArgs e) => RefreshList();

        /// <summary>
        /// Observer setup to keep the list updated with changes in the BL.
        /// </summary>
        private void courierListObserver() => Dispatcher.Invoke(RefreshList);

        /// <summary>
        /// Registers the observer when the window is loaded.
        /// </summary>
        private void Window_Loaded(object sender, RoutedEventArgs e) => s_bl.Courier.AddObserver(courierListObserver);

        /// <summary>
        /// Unregisters the observer when the window is closed.
        /// </summary>
        private void Window_Closed(object sender, EventArgs e) => s_bl.Courier.RemoveObserver(courierListObserver);

        /// <summary>
        /// Opens the CourierWindow in Update mode when a row is double-clicked.
        /// </summary>
        private void DataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            if (sender is DataGrid grid && grid.SelectedItem is BO.CourierInList courier)
                new CourierWindow(courier.Id).Show();
        }

        /// <summary>
        /// Opens the CourierWindow in Add mode.
        /// </summary>
        private void BtnAdd_Click(object sender, RoutedEventArgs e)
        {
            new CourierWindow().Show();
        }

        /// <summary>
        /// Deletes the selected courier after confirmation.
        /// </summary>
        private void BtnDelete_Click(object sender, RoutedEventArgs e)
        {
            if (sender is Button btn && btn.DataContext is BO.CourierInList courier)
            {
                if (MessageBox.Show($"Are you sure you want to delete courier {courier.Id}?", "Delete Confirmation", MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes)
                {
                    try
                    {
                        s_bl.Courier.Delete(courier.Id);
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show(ex.Message, "Deletion Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    }
                }
            }
        }
    }
