﻿﻿﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace PL.Courier;

    /// <summary>
    /// Interaction logic for CourierListWindow.xaml
    /// </summary>
    public partial class CourierListWindow : Window
    {
        // Access to the Business Layer
        static readonly BlApi.IBl s_bl = BlApi.Factory.Get();

        public object StatusFilter
        {
            get { return (object)GetValue(StatusFilterProperty); }
            set { SetValue(StatusFilterProperty, value); }
        }
        public static readonly DependencyProperty StatusFilterProperty =
            DependencyProperty.Register("StatusFilter", typeof(object), typeof(CourierListWindow), new PropertyMetadata("None"));

        // Dependency Property for the list of couriers bound to the DataGrid
        public IEnumerable<BO.CourierInList> CourierList
        {
            get { return (IEnumerable<BO.CourierInList>)GetValue(CourierListProperty); }
            set { SetValue(CourierListProperty, value); }
        }

        public static readonly DependencyProperty CourierListProperty =
            DependencyProperty.Register("CourierList", typeof(IEnumerable<BO.CourierInList>), typeof(CourierListWindow), new PropertyMetadata(null));

        // The currently selected courier in the DataGrid
        public BO.CourierInList? SelectedCourier
        {
            get { return (BO.CourierInList?)GetValue(SelectedCourierProperty); }
            set { SetValue(SelectedCourierProperty, value); }
        }

        public static readonly DependencyProperty SelectedCourierProperty =
            DependencyProperty.Register("SelectedCourier", typeof(BO.CourierInList), typeof(CourierListWindow), new PropertyMetadata(null));

        public ICommand DeleteSingleCommand { get; }

        public CourierListWindow()
        {
            InitializeComponent();
            DeleteSingleCommand = new RelayCommand(DeleteSingleCourier);
        }

        /// <summary>
        /// Refreshes the courier list based on the selected filter.
        /// </summary>
        private void RefreshList()
        {
            CourierList = (StatusFilter is BO.DeliveryTypes type)
                ? s_bl.Courier.ReadAll(c => c.DeliveryType == type)
                : s_bl.Courier.ReadAll();
        }

        /// <summary>
        /// Event handler for filter selection change.
        /// </summary>
        private void cbStatusSelector_SelectionChanged(object sender, SelectionChangedEventArgs e) => RefreshList();

        /// <summary>
        /// Observer setup to keep the list updated with changes in the BL.
        /// </summary>
        private void courierListObserver() => Dispatcher.Invoke(RefreshList);

        /// <summary>
        /// Registers the observer when the window is loaded.
        /// </summary>
        private void Window_Loaded(object sender, RoutedEventArgs e) => s_bl.Courier.AddObserver(courierListObserver);

        /// <summary>
        /// Unregisters the observer when the window is closed.
        /// </summary>
        private void Window_Closed(object sender, EventArgs e) => s_bl.Courier.RemoveObserver(courierListObserver);

        /// <summary>
        /// Opens the CourierWindow in Update mode when a row is double-clicked.
        /// </summary>
        private void DataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            if (SelectedCourier != null)
                new CourierWindow(SelectedCourier.Id).Show();
        }

        /// <summary>
        /// Opens the CourierWindow in Add mode.
        /// </summary>
        private void BtnAdd_Click(object sender, RoutedEventArgs e)
        {
            new CourierWindow().Show();
        }

        /// <summary>
        /// Deletes a specific courier by ID after confirmation.
        /// </summary>
        /// <param name="parameter">The ID of the courier to delete.</param>
        private void DeleteSingleCourier(object parameter)
        {
            if (parameter is int id)
            {
                if (MessageBox.Show($"Are you sure you want to delete courier {id}?", "Delete Confirmation", MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes)
                {
                    try
                    {
                        s_bl.Courier.Delete(id);
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show(ex.Message, "Deletion Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    }
                }
            }
        }
    }

    /// <summary>
    /// A basic implementation of ICommand to handle commands from the UI.
    /// </summary>
    public class RelayCommand : ICommand
    {
        private readonly Action<object> _execute;
        private readonly Predicate<object>? _canExecute;

        public RelayCommand(Action<object> execute, Predicate<object>? canExecute = null)
        {
            _execute = execute;
            _canExecute = canExecute;
        }

        public bool CanExecute(object? parameter) => _canExecute == null || _canExecute(parameter!);
        public void Execute(object? parameter) => _execute(parameter!);
        public event EventHandler? CanExecuteChanged
        {
            add { CommandManager.RequerySuggested += value; }
            remove { CommandManager.RequerySuggested -= value; }
        }
    }
