﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace PL.Order;

/// <summary>
/// Interaction logic for OrderInListWindow.xaml
/// </summary>
public partial class OrderListWindow : Window
{
    // Access to Business Layer
    static readonly BlApi.IBl s_bl = BlApi.Factory.Get();

    public object StatusFilter { get; set; } = "None";
    public object TypeFilter { get; set; } = "None";
    public object ScheduleStatusFilter { get; set; } = "None";

    // Dependency Property for Order List
    public IEnumerable<BO.OrderInList> OrderList
    {
        get { return (IEnumerable<BO.OrderInList>)GetValue(OrderListProperty); }
        set { SetValue(OrderListProperty, value); }
    }

    public static readonly DependencyProperty OrderListProperty =
        DependencyProperty.Register("OrderList", typeof(IEnumerable<BO.OrderInList>), typeof(OrderListWindow), new PropertyMetadata(null));

    // Selected Order
    public BO.OrderInList? SelectedOrder
    {
        get { return (BO.OrderInList?)GetValue(SelectedOrderProperty); }
        set { SetValue(SelectedOrderProperty, value); }
    }

    public static readonly DependencyProperty SelectedOrderProperty =
        DependencyProperty.Register("SelectedOrder", typeof(BO.OrderInList), typeof(OrderListWindow), new PropertyMetadata(null));

    public OrderListWindow()
    {
        InitializeComponent();
    }

    /// <summary>
    /// Refresh list with all 3 filters applied.
    /// </summary>
    private void RefreshList()
    {
        var orders = s_bl.Order.ReadAll();

        if (StatusFilter is BO.OrderStatus status)
            orders = orders.Where(o => o.OrderStatus == status);

        if (TypeFilter is BO.OrderTypes type)
            orders = orders.Where(o => o.OrderType == type);

        if (ScheduleStatusFilter is BO.ScheduleStatus scheduleStatus)
            orders = orders.Where(o => o.ScheduleStatus == scheduleStatus);

        OrderList = orders;
    }

    /// <summary>
    /// Event handler for status filter selection change.
    /// </summary>
    private void cbStatusSelector_SelectionChanged(object sender, SelectionChangedEventArgs e) => RefreshList();

    /// <summary>
    /// Event handler for general filter selection change.
    /// </summary>
    private void cbFilter_SelectionChanged(object sender, SelectionChangedEventArgs e) => RefreshList();

    /// <summary>
    /// Observer setup to keep the list updated.
    /// </summary>
    private void orderListObserver() => Dispatcher.Invoke(RefreshList);

    /// <summary>
    /// Registers the observer when the window is loaded.
    /// </summary>
    private void Window_Loaded(object sender, RoutedEventArgs e) => s_bl.Order.AddObserver(orderListObserver);

    /// <summary>
    /// Unregisters the observer when the window is closed.
    /// </summary>
    private void Window_Closed(object sender, EventArgs e) => s_bl.Order.RemoveObserver(orderListObserver);

    /// <summary>
    /// Open OrderWindow in Update mode.
    /// </summary>
    private void DataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
    {
        if (SelectedOrder != null)
            new OrderWindow(SelectedOrder.Id).Show();
    }

    /// <summary>
    /// Open OrderWindow in Add mode.
    /// </summary>
    private void BtnAdd_Click(object sender, RoutedEventArgs e)
    {
        new OrderWindow().Show();
    }

    /// <summary>
    /// Cancel Order logic.
    /// </summary>
    private void BtnCancel_Click(object sender, RoutedEventArgs e)
    {
        if (sender is Button btn && btn.DataContext is BO.OrderInList order)
        {
            if (MessageBox.Show($"Are you sure you want to cancel order {order.Id}?", "Cancel Confirmation", MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes)
            {
                try
                {
                    s_bl.Order.Cancel(order.Id);
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.Message, "Cancellation Error", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }
    }
}
