﻿﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace PL.Order;

/// <summary>
/// Interaction logic for OrderInListWindow.xaml
/// </summary>
public partial class OrderListWindow : Window
{
    // Access to Business Layer
    static readonly BlApi.IBl s_bl = BlApi.Factory.Get();

    public object StatusFilter
    {
        get { return (object)GetValue(StatusFilterProperty); }
        set { SetValue(StatusFilterProperty, value); }
    }
    public static readonly DependencyProperty StatusFilterProperty =
        DependencyProperty.Register("StatusFilter", typeof(object), typeof(OrderListWindow), new PropertyMetadata("None"));

    public object TypeFilter
    {
        get { return (object)GetValue(TypeFilterProperty); }
        set { SetValue(TypeFilterProperty, value); }
    }
    public static readonly DependencyProperty TypeFilterProperty =
        DependencyProperty.Register("TypeFilter", typeof(object), typeof(OrderListWindow), new PropertyMetadata("None"));

    public object ScheduleStatusFilter
    {
        get { return (object)GetValue(ScheduleStatusFilterProperty); }
        set { SetValue(ScheduleStatusFilterProperty, value); }
    }
    public static readonly DependencyProperty ScheduleStatusFilterProperty =
        DependencyProperty.Register("ScheduleStatusFilter", typeof(object), typeof(OrderListWindow), new PropertyMetadata("None"));

    // Dependency Property for Order List
    public IEnumerable<BO.OrderInList> OrderList
    {
        get { return (IEnumerable<BO.OrderInList>)GetValue(OrderListProperty); }
        set { SetValue(OrderListProperty, value); }
    }

    public static readonly DependencyProperty OrderListProperty =
        DependencyProperty.Register("OrderList", typeof(IEnumerable<BO.OrderInList>), typeof(OrderListWindow), new PropertyMetadata(null));

    // Selected Order
    public BO.OrderInList? SelectedOrder
    {
        get { return (BO.OrderInList?)GetValue(SelectedOrderProperty); }
        set { SetValue(SelectedOrderProperty, value); }
    }

    public static readonly DependencyProperty SelectedOrderProperty =
        DependencyProperty.Register("SelectedOrder", typeof(BO.OrderInList), typeof(OrderListWindow), new PropertyMetadata(null));

    public ICommand CancelSingleCommand { get; }

    public OrderListWindow()
    {
        InitializeComponent();
        CancelSingleCommand = new RelayCommand(CancelSingleOrder, CanCancelOrder);
    }

    /// <summary>
    /// Refresh list with all 3 filters applied.
    /// </summary>
    private void RefreshList()
    {
        var orders = s_bl.Order.ReadAll();

        if (StatusFilter is BO.OrderStatus status)
            orders = orders.Where(o => o.OrderStatus == status);

        if (TypeFilter is BO.OrderTypes type)
            orders = orders.Where(o => o.OrderType == type);

        if (ScheduleStatusFilter is BO.ScheduleStatus scheduleStatus)
            orders = orders.Where(o => o.ScheduleStatus == scheduleStatus);

        OrderList = orders;
    }

    /// <summary>
    /// Event handler for status filter selection change.
    /// </summary>
    private void cbStatusSelector_SelectionChanged(object sender, SelectionChangedEventArgs e) => RefreshList();

    /// <summary>
    /// Event handler for general filter selection change.
    /// </summary>
    private void cbFilter_SelectionChanged(object sender, SelectionChangedEventArgs e) => RefreshList();

    /// <summary>
    /// Observer setup to keep the list updated.
    /// </summary>
    private void orderListObserver() => Dispatcher.Invoke(RefreshList);

    /// <summary>
    /// Registers the observer when the window is loaded.
    /// </summary>
    private void Window_Loaded(object sender, RoutedEventArgs e)
    {
        s_bl.Order.AddObserver(orderListObserver);
        s_bl.Admin.AddClockObserver(orderListObserver);
        Activate();
    }

    /// <summary>
    /// Unregisters the observer when the window is closed.
    /// </summary>
    private void Window_Closed(object sender, EventArgs e)
    {
        s_bl.Order.RemoveObserver(orderListObserver);
        s_bl.Admin.RemoveClockObserver(orderListObserver);
    }

    /// <summary>
    /// Open OrderWindow in Update mode.
    /// </summary>
    private void DataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
    {
        if (SelectedOrder != null)
            Tools.OpenWindow(() => new OrderWindow(SelectedOrder.Id), predicate: w => w.ButtonText == "Update", replace: true);
    }

    /// <summary>
    /// Open OrderWindow in Add mode.
    /// </summary>
    private void BtnAdd_Click(object sender, RoutedEventArgs e)
    {
        Tools.OpenWindow(() => new OrderWindow(), predicate: w => w.ButtonText == "Add", replace: false);
    }

    /// <summary>
    /// Cancels a specific order by ID after confirmation.
    /// </summary>
    /// <param name="parameter">The ID of the order to cancel.</param>
    private void CancelSingleOrder(object parameter)
    {
        if (parameter is BO.OrderInList order)
        {
            if (MessageBox.Show(this, $"Are you sure you want to cancel order {order.Id}?", "Cancel Confirmation", MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes)
            {
                try
                {
                    s_bl.Order.Cancel(order.Id);
                }
                catch (Exception ex)
                {
                    MessageBox.Show(this, ex.Message, "Cancellation Error", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }
    }

    private bool CanCancelOrder(object parameter)
    {
        return parameter is BO.OrderInList order &&
               (order.OrderStatus == BO.OrderStatus.Open || order.OrderStatus == BO.OrderStatus.InProgress);
    }
}

/// <summary>
/// A basic implementation of ICommand to handle commands from the UI.
/// </summary>
public class RelayCommand : ICommand
{
    private readonly Action<object> _execute;
    private readonly Predicate<object>? _canExecute;

    public RelayCommand(Action<object> execute, Predicate<object>? canExecute = null)
    {
        _execute = execute;
        _canExecute = canExecute;
    }

    public bool CanExecute(object? parameter) => _canExecute == null || _canExecute(parameter!);
    public void Execute(object? parameter) => _execute(parameter!);
    public event EventHandler? CanExecuteChanged
    {
        add { CommandManager.RequerySuggested += value; }
        remove { CommandManager.RequerySuggested -= value; }
    }
}
