﻿﻿﻿﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System;
using System.Text;
using System.Windows;
using BlApi;
using PL;

namespace PL.Order;

/// <summary>
/// Interaction logic for OrderWindow.xaml
/// </summary>
public partial class OrderWindow : Window
{
    // Access to Business Layer
    private static IBl s_bl = Factory.Get();

    public BO.Order CurrentOrder
    {
        get { return (BO.Order)GetValue(CurrentOrderProperty); }
        set { SetValue(CurrentOrderProperty, value); }
    }

    // Dependency Property for Order entity
    public static readonly DependencyProperty CurrentOrderProperty =
        DependencyProperty.Register("CurrentOrder", typeof(BO.Order), typeof(OrderWindow), new PropertyMetadata(null));

    // Button Text ("Add" or "Update")
    public string ButtonText
    {
        get { return (string)GetValue(ButtonTextProperty); }
        set { SetValue(ButtonTextProperty, value); }
    }

    public static readonly DependencyProperty ButtonTextProperty =
        DependencyProperty.Register("ButtonText", typeof(string), typeof(OrderWindow), new PropertyMetadata("Add"));

    /// <summary>
    /// Constructor for OrderWindow.
    /// </summary>
    /// <param name="id">Order ID (0 for new).</param>
    public OrderWindow(int id = 0)
    {
        ButtonText = id == 0 ? "Add" : "Update";
        InitializeComponent();
        Init(id);
    }

    /// <summary>
    /// Initialize window state.
    /// </summary>
    private void Init(int id)
    {
        try
        {
            // Register for clock updates to keep the time current for new orders
            s_bl.Admin.AddClockObserver(Observer);
            if (id == 0)
            {
                // Add Mode: Default values
                CurrentOrder = new BO.Order
                {
                    OrderOpenTime = s_bl.Admin.GetClock(),
                    OrderStatus = BO.OrderStatus.Open,
                    OrderType = BO.OrderTypes.Pizza // Default
                };
            }
            else
            {
                // Update Mode: Load order and register observer
                CurrentOrder = s_bl.Order.Read(id);
                s_bl.Order.AddObserver(id, Observer);
            }
            Closing += (s, e) =>
            {
                s_bl.Admin.RemoveClockObserver(Observer);
                if (id != 0) s_bl.Order.RemoveObserver(id, Observer);
            };
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            Close();
        }
    }

    /// <summary>
    /// Observer to refresh order data.
    /// </summary>
    private void Observer()
    {
        Dispatcher.Invoke(() => 
        {
            if (CurrentOrder != null && CurrentOrder.Id != 0)
                CurrentOrder = s_bl.Order.Read(CurrentOrder.Id);
            else if (CurrentOrder != null)
                // In Add mode, keep the creation time synced with the system clock until saved
                CurrentOrder.OrderOpenTime = s_bl.Admin.GetClock();
        });
    }

    /// <summary>
    /// Handle Add/Update action.
    /// </summary>
    private void BtnAddUpdate_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            string uiErrors = Tools.GetUiValidationErrors(this);
            bool hasUiErrors = !string.IsNullOrEmpty(uiErrors);

            if (ButtonText == "Update")
            {
                var original = s_bl.Order.Read(CurrentOrder.Id);
                // Ignore calculated properties or those not editable by user
                bool hasValidChanges = Tools.IsInstanceChanged(original, CurrentOrder, nameof(BO.Order.TimeOpenedDuration), nameof(BO.Order.OrderStatus), nameof(BO.Order.ScheduleStatus));

                if (!hasValidChanges && !hasUiErrors)
                {
                    MessageBox.Show(this, "No changes were made.", "Information", MessageBoxButton.OK, MessageBoxImage.Information);
                    Close();
                    return;
                }
                
                if (!hasValidChanges && hasUiErrors)
                {
                    MessageBox.Show(this, $"Invalid input:\n{uiErrors}", "Invalid Input", MessageBoxButton.OK, MessageBoxImage.Warning);
                    var temp = CurrentOrder;
                    CurrentOrder = null;
                    CurrentOrder = temp;
                    return;
                }
            }

            if (ButtonText == "Add")
                s_bl.Order.Create(CurrentOrder);
            else
                s_bl.Order.Update(CurrentOrder);
            
            if (hasUiErrors)
            {
                MessageBox.Show(this, $"Partial Success: Valid changes were saved.\n\nInvalid format inputs were reverted:\n{uiErrors}", "Partial Success", MessageBoxButton.OK, MessageBoxImage.Information);
                
                var temp = CurrentOrder;
                CurrentOrder = null;
                CurrentOrder = temp;
            }
            else
            {
                MessageBox.Show(this, $"Order {(ButtonText == "Add" ? "Added" : "Updated")} successfully!", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
                Close();
            }
        }
        catch (BO.BlInvalidInputException ex)
        {
            string uiErrors = Tools.GetUiValidationErrors(this);
            bool hasUiErrors = !string.IsNullOrEmpty(uiErrors);
            StringBuilder msg = new StringBuilder();
            if (hasUiErrors) msg.AppendLine("Invalid format inputs:").AppendLine(uiErrors);

            // Revert invalid fields to original values if in Update mode
            if (ButtonText == "Update" && ex.ValidationErrors.Count > 0)
            {
                var original = s_bl.Order.Read(CurrentOrder.Id);
                Tools.RevertInvalidProperties(CurrentOrder, original, ex.ValidationErrors);

                // Force UI refresh by re-assigning the property
                var temp = CurrentOrder;
                CurrentOrder = null;
                CurrentOrder = temp;

                // Retry saving valid changes
                if (Tools.IsInstanceChanged(original, CurrentOrder, nameof(BO.Order.TimeOpenedDuration), nameof(BO.Order.OrderStatus), nameof(BO.Order.ScheduleStatus)))
                {
                    try
                    {
                        s_bl.Order.Update(CurrentOrder);
                        MessageBox.Show(this, $"Partial Success: Invalid values were reverted. Valid changes were saved.\n\nDetails:\n{msg}{ex.Message}", "Partial Success", MessageBoxButton.OK, MessageBoxImage.Information);
                        return;
                    }
                    catch (Exception retryEx)
                    {
                        msg.AppendLine($"Retry failed: {retryEx.Message}");
                    }
                }
            }
            
            MessageBox.Show(this, msg.Append(ex.Message).ToString(), "Invalid Input", MessageBoxButton.OK, MessageBoxImage.Warning);
            if (hasUiErrors)
            {
                var temp = CurrentOrder;
                CurrentOrder = null;
                CurrentOrder = temp;
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            // Revert to original state if update failed to ensure UI matches DB state
            if (ButtonText == "Update")
            {
                try
                {
                    CurrentOrder = s_bl.Order.Read(CurrentOrder.Id);
                }
                catch
                {
                    Close(); // If entity no longer exists or read fails, close window
                }
            }
        }
    }
}