﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System;
using System.Windows;
using BlApi;
using PL;

namespace PL.Order;

/// <summary>
/// Interaction logic for OrderWindow.xaml
/// </summary>
public partial class OrderWindow : Window
{
    // Access to Business Layer
    private static IBl s_bl = Factory.Get();

    public BO.Order CurrentOrder
    {
        get { return (BO.Order)GetValue(CurrentOrderProperty); }
        set { SetValue(CurrentOrderProperty, value); }
    }

    // Dependency Property for Order entity
    public static readonly DependencyProperty CurrentOrderProperty =
        DependencyProperty.Register("CurrentOrder", typeof(BO.Order), typeof(OrderWindow), new PropertyMetadata(null));

    // Button Text ("Add" or "Update")
    public string ButtonText
    {
        get { return (string)GetValue(ButtonTextProperty); }
        set { SetValue(ButtonTextProperty, value); }
    }

    public static readonly DependencyProperty ButtonTextProperty =
        DependencyProperty.Register("ButtonText", typeof(string), typeof(OrderWindow), new PropertyMetadata("Add"));

    /// <summary>
    /// Constructor for OrderWindow.
    /// </summary>
    /// <param name="id">Order ID (0 for new).</param>
    public OrderWindow(int id = 0)
    {
        ButtonText = id == 0 ? "Add" : "Update";
        InitializeComponent();
        Init(id);
    }

    /// <summary>
    /// Initialize window state.
    /// </summary>
    private void Init(int id)
    {
        try
        {
            if (id == 0)
            {
                // Add Mode: Default values
                CurrentOrder = new BO.Order
                {
                    OrderOpenTime = s_bl.Admin.GetClock(),
                    OrderStatus = BO.OrderStatus.Open,
                    OrderType = BO.OrderTypes.Pizza // Default
                };
            }
            else
            {
                // Update Mode: Load order and register observer
                CurrentOrder = s_bl.Order.Read(id);
                s_bl.Order.AddObserver(id, Observer);
                Closing += (s, e) => s_bl.Order.RemoveObserver(id, Observer);
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            Close();
        }
    }

    /// <summary>
    /// Observer to refresh order data.
    /// </summary>
    private void Observer()
    {
        Dispatcher.Invoke(() => CurrentOrder = s_bl.Order.Read(CurrentOrder.Id));
    }

    /// <summary>
    /// Handle Add/Update action.
    /// </summary>
    private void BtnAddUpdate_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            if (ButtonText == "Add")
                s_bl.Order.Create(CurrentOrder);
            else
                s_bl.Order.Update(CurrentOrder);
            
            MessageBox.Show($"Order {ButtonText}ed successfully!", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
            Close();
        }
        catch (BO.BlInvalidInputException ex)
        {
            MessageBox.Show(ex.Message, "Invalid Input", MessageBoxButton.OK, MessageBoxImage.Warning);
            
            // Revert invalid fields to original values if in Update mode
            if (ButtonText == "Update" && ex.ValidationErrors.Count > 0)
            {
                var original = s_bl.Order.Read(CurrentOrder.Id);
                foreach (var error in ex.ValidationErrors)
                {
                    var prop = typeof(BO.Order).GetProperty(error.Key);
                    if (prop != null && prop.CanWrite)
                    {
                        prop.SetValue(CurrentOrder, prop.GetValue(original));
                    }
                }
                // Force UI refresh by re-assigning the property
                var temp = CurrentOrder;
                CurrentOrder = null;
                CurrentOrder = temp;
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }
}