﻿﻿﻿﻿﻿﻿﻿﻿﻿// Generated by gemini, prompt in readme under stage 4
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;


namespace Helpers;

/// <summary>
/// Manager class for Courier entity operations, providing conversion methods
/// between data layer (DO) and business layer (BO) representations.
/// </summary>
internal static class CourierManager
{
    private static DalApi.IDal s_dal = DalApi.Factory.Get;
    internal static ObserverManager Observers = new();

    /// <summary>
    /// Validates a business layer Courier entity.
    /// </summary>
    /// <param name="boCourier">The BO Courier to validate.</param>
    /// <exception cref="BO.BlInvalidNullInputException">Thrown if the courier is null.</exception>
    /// <exception cref="BO.BlInvalidIdException">Thrown if the courier ID is invalid.</exception>
    /// <exception cref="BO.BlInvalidInputException">Thrown if required fields are empty.</exception>
    /// <exception cref="BO.BlInvalidEmailException">Thrown if the email format is invalid.</exception>
    public static void CourierValidation(BO.Courier boCourier)
    {
        var errors = new Dictionary<string, string>();
        if (boCourier == null)
            throw new BO.BlInvalidNullInputException("Courier object cannot be null.");
            
        if ((boCourier.Id < 100000000 || boCourier.Id > 999999999))
            errors[nameof(BO.Courier.Id)] = $"Courier ID '{boCourier.Id}' is not valid. It must be a 9-digit number.";

        if (boCourier.FullName != null && boCourier.FullName.Length > 60)
            errors[nameof(BO.Courier.FullName)] = "Courier full name is too long.";
        else
        {
            var nameError = Tools.ValidateFullName(boCourier.FullName, "Courier full name");
            if (nameError != null) errors[nameof(BO.Courier.FullName)] = nameError;
        }

        var phoneError = Tools.ValidatePhoneNumber(boCourier.MobilePhone, "Courier mobile phone");
        if (phoneError != null) errors[nameof(BO.Courier.MobilePhone)] = phoneError;

        var emailError = Tools.ValidateEmail(boCourier.Email, "Courier email");
        if (emailError != null) errors[nameof(BO.Courier.Email)] = emailError;

        if (string.IsNullOrWhiteSpace(boCourier.Password))
            errors[nameof(BO.Courier.Password)] = "Courier password cannot be empty.";
        else if (boCourier.Password.Length > 100)
            errors[nameof(BO.Courier.Password)] = "Courier password is too long.";

        if (boCourier.PersonalMaxDeliveryDistance.HasValue && boCourier.PersonalMaxDeliveryDistance <= 0)
            errors[nameof(BO.Courier.PersonalMaxDeliveryDistance)] = "Personal max delivery distance must be positive.";
        else if (boCourier.PersonalMaxDeliveryDistance.HasValue && boCourier.PersonalMaxDeliveryDistance > 20000)
            errors[nameof(BO.Courier.PersonalMaxDeliveryDistance)] = "Personal max delivery distance is too large.";

        if (!Enum.IsDefined(typeof(BO.DeliveryTypes), boCourier.DeliveryType))
            errors[nameof(BO.Courier.DeliveryType)] = "Invalid delivery type.";

        if (errors.Any())
            throw new BO.BlInvalidInputException(string.Join(Environment.NewLine, errors.Values)) { ValidationErrors = errors };
    }

    /// <summary>
    /// Retrieves a single courier and calculates their employment duration.
    /// </summary>
    /// <param name="courierId">The ID of the courier to retrieve.</param>
    /// <returns>A BO.Courier object with calculated properties.</returns>
    /// <exception cref="BO.BlDoesNotExistException">Thrown if the courier is not found.</exception>
    public static BO.Courier ReadCourier(int courierId)
    {
        try
        {
            DO.Courier? doCourier = s_dal.Courier.Read(courierId);
            if (doCourier == null)
                throw new BO.BlDoesNotExistException($"Courier with ID {courierId} not found.");
            return ConvertDoToBo(doCourier!);
        }
        catch (DO.DalDoesNotExistException ex)
        {
            throw new BO.BlDoesNotExistException($"Courier with ID {courierId} not found.", ex);
        }
    }

    /// <summary>
    /// Retrieves a list of all couriers, converted to full business objects, with optional filtering.
    /// </summary>
    /// <param name="filter">An optional predicate to filter the BO.Courier objects.</param>
    /// <returns>An IEnumerable of BO.Courier.</returns>
    public static IEnumerable<BO.Courier> ReadAll(Func<BO.Courier, bool>? filter = null)
    {
        // Optimization: Fetch all active deliveries once to identify busy couriers. (checking if active is resource intensive - requires deliveries readall)
        // Using ToHashSet allows for O(1) lookup complexity inside the projection.
        var activeCourierIds = s_dal.Delivery.ReadAll(d => d.DeliveryEndTime == null)
                                             .Select(d => d.CourierId)
                                             .ToHashSet();

        var boCouriers = s_dal.Courier.ReadAll().Where(c => c != null)
                                      .Select(c => ConvertDoToBo(c!, activeCourierIds.Contains(c!.Id)));
                                      
        return filter == null ? boCouriers : boCouriers.Where(filter);
    }

    /// <summary>
    /// Creates a new courier in the data source.
    /// </summary>
    /// <param name="courier">The courier to create.</param>
    /// <exception cref="BO.BlAlreadyExistsException">Thrown if a courier with the same ID already exists.</exception>
    public static void CreateCourier(BO.Courier courier)
    {
        try
        {
            s_dal.Courier.Create(ConvertBoToDo(courier));
            Observers.NotifyListUpdated();
        }
        catch (DO.DalAlreadyExistsException ex)
        {
            throw new BO.BlAlreadyExistsException($"Courier with ID {courier.Id} already exists.", ex);
        }
    }

    /// <summary>
    /// Deletes a courier from the data source.
    /// </summary>
    /// <param name="courierId">The ID of the courier to delete.</param>
    /// <exception cref="BO.BlDoesNotExistException">Thrown if the courier is not found.</exception>
    public static void DeleteCourier(int courierId)
    {
        try
        {
            // We might want to check if the courier has active deliveries before deleting
            if (IsCourierInDelivery(courierId))
                throw new BO.BlDeliveryInProgressException();
            s_dal.Courier.Delete(courierId);
            Observers.NotifyListUpdated();
            Observers.NotifyItemUpdated(courierId);
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }

    /// <summary>
    /// Updates an existing courier's details.
    /// </summary>
    /// <param name="courier">The courier with updated details.</param>
    /// <exception cref="BO.BlDoesNotExistException">Thrown if the courier is not found.</exception>
    public static void UpdateCourier(BO.Courier courier)
    {
        try
        {
            // Read the existing courier from the database.
            var existingCourier = ReadCourier(courier.Id);

            // Check if courier has an active delivery
            if (IsCourierInDelivery(courier.Id))
            {
                // If any property besides the allowed ones is changed, throw exception
                if (existingCourier.Active != courier.Active ||
                    existingCourier.DeliveryType != courier.DeliveryType)
                {
                    throw new BO.BlDeliveryInProgressException(
                        $"Cannot update certain courier properties for courier ID '{courier.Id}' while a delivery is in progress.");
                }
            }
            
            // Update only the properties that an admin is allowed to change.
            existingCourier.FullName = courier.FullName;
            existingCourier.MobilePhone = courier.MobilePhone;
            existingCourier.Email = courier.Email;
            existingCourier.Password = courier.Password;
            existingCourier.Active = courier.Active;
            existingCourier.PersonalMaxDeliveryDistance = courier.PersonalMaxDeliveryDistance;
            existingCourier.DeliveryType = courier.DeliveryType;

            // Save the updated courier to the database.
            s_dal.Courier.Update(ConvertBoToDo(existingCourier));
            Observers.NotifyItemUpdated(courier.Id);
            Observers.NotifyListUpdated();
        }
        catch (DO.DalDoesNotExistException ex)
        {
            throw new BO.BlDoesNotExistException($"Courier with ID {courier.Id} not found.", ex);
        }
    }

    /// <summary>
    /// Updates a courier's own details.
    /// </summary>
    /// <param name="courierId">The ID of the courier to update.</param>
    /// <param name="fullName">Optional new full name.</param>
    /// <param name="phoneNum">Optional new phone number.</param>
    /// <param name="email">Optional new email.</param>
    /// <param name="password">Optional new password.</param>
    /// <param name="maxDistance">Optional new max delivery distance.</param>
    public static void UpdateMyDetails(int courierId, string? fullName = null, string? phoneNum = null, string? email = null, string? password = null, double? maxDistance = null, BO.DeliveryTypes? deliveryType = null)
    {
        try
        {
            var courier = ReadCourier(courierId); // Read once at the beginning

            // Check if courier has an active delivery
            if (IsCourierInDelivery(courierId))
            {
                // If in delivery, only allow certain fields to be updated.
                // DeliveryType is not one of them.
                if (deliveryType.HasValue && courier.DeliveryType != deliveryType)
                {
                    throw new BO.BlDeliveryInProgressException(
                        $"Cannot update DeliveryType for courier ID '{courierId}' while a delivery is in progress.");
                }
            }

            // Update properties using the ?? operator for conciseness
            courier.FullName = fullName ?? courier.FullName;
            courier.MobilePhone = phoneNum ?? courier.MobilePhone;
            courier.Email = email ?? courier.Email;
            courier.Password = password ?? courier.Password;
            courier.PersonalMaxDeliveryDistance = maxDistance ?? courier.PersonalMaxDeliveryDistance;
            courier.DeliveryType = deliveryType ?? courier.DeliveryType;

            // Now, call the DAL update directly.
            s_dal.Courier.Update(ConvertBoToDo(courier));
            Observers.NotifyItemUpdated(courierId);
            Observers.NotifyListUpdated();
        }
        catch (DO.DalDoesNotExistException ex)
        {
            // The exception could come from ReadCourier or the s_dal.Courier.Update call.
            // The message is appropriate for both cases.
            throw new BO.BlDoesNotExistException($"Courier with ID {courierId} not found.", ex);
        }
    }

    /// <summary>
    /// Checks if a courier is in middle of a delivery.
    /// </summary>
    /// <param name="courierId">The ID of the courier to update.</param>
    /// /// <returns>True if courier is in middle of a delivery.</returns>
    /// <exception cref="BO.BlDoesNotExistException">Thrown if courier doesn't exist.</exception>
    public static bool IsCourierInDelivery(int courierId)
    {   
        try
        {
            if (s_dal.Courier.Read(courierId) == null)
                return false;
            return s_dal.Delivery.ReadAll(d => d.CourierId == courierId && d.DeliveryEndTime == null).Any();
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }

    

    /// <summary>
    /// Converts a business layer Courier entity to its data layer equivalent.
    /// </summary>
    /// <param name="boCourier">The BO Courier to convert.</param>
    /// <returns>An equivalent DO Courier entity.</returns>
    /// <exception cref="BO.BlInvalidInputException">Thrown when conversion fails.</exception>
    public static DO.Courier ConvertBoToDo(BO.Courier boCourier)
    {
        CourierValidation(boCourier);
        try
        {
            return new DO.Courier(
                Id: boCourier.Id,
                FullName: boCourier.FullName,
                MobilePhone: boCourier.MobilePhone,
                Email: boCourier.Email,
                Password: boCourier.Password,
                Active: boCourier.Active,
                DeliveryType: (DO.DeliveryTypes)boCourier.DeliveryType,
                EmploymentStartTime: boCourier.EmploymentStartTime,
                PersonalMaxDeliveryDistance: boCourier.PersonalMaxDeliveryDistance
            );
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }

    /// <summary>
    /// Converts a data layer Courier entity to its business layer equivalent.
    /// </summary>
    /// <param name="doCourier">The DO Courier to convert.</param>
    /// <returns>An equivalent BO Courier entity.</returns>
    /// <exception cref="BO.BlInvalidInputException">Thrown when conversion fails.</exception>
    public static BO.Courier ConvertDoToBo(DO.Courier doCourier)
    {
        // Default behavior: Check DB for active delivery (slower for lists)
        return ConvertDoToBo(doCourier, IsCourierInDelivery(doCourier.Id));
    }

    /// <summary>
    /// Private helper to convert DO to BO when IsInDelivery status is already known.
    /// </summary>
    /// <param name="doCourier">The DO Courier.</param>
    /// <param name="isInDelivery">Pre-calculated delivery status.</param>
    /// <returns>BO Courier.</returns>
    private static BO.Courier ConvertDoToBo(DO.Courier doCourier, bool isInDelivery)
    {
        try
        {
            var boCourier = new BO.Courier
            {
                Id = doCourier.Id,
                FullName = doCourier.FullName,
                MobilePhone = doCourier.MobilePhone,
                Email = doCourier.Email,
                Password = doCourier.Password,
                Active = doCourier.Active,
                DeliveryType = (BO.DeliveryTypes)doCourier.DeliveryType,
                EmploymentStartTime = doCourier.EmploymentStartTime,
                PersonalMaxDeliveryDistance = doCourier.PersonalMaxDeliveryDistance
            };

            boCourier.YearsEmployed = Math.Round((AdminManager.Now - boCourier.EmploymentStartTime).TotalDays / 365.25, 2);
            boCourier.IsInDelivery = isInDelivery;
            
            return boCourier;
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }

    /// <summary>
    /// Converts a business layer Courier entity to a summary list view.
    /// Summary entities are derived from full BO entities (not directly from DO)
    /// to ensure calculated properties and validations are preserved.
    /// </summary>
    /// <param name="boCourier">The BO Courier to convert.</param>
    /// <returns>A CourierInList summary entity.</returns>
    /// <exception cref="BO.BlInvalidInputException">Thrown when conversion fails.</exception>
    public static BO.CourierInList ConvertBoToCourierInList(BO.Courier boCourier)
    {
        try
        {
            return new BO.CourierInList
            {
                Id = boCourier.Id,
                FullName = boCourier.FullName,
                DeliveryType = boCourier.DeliveryType,
                Active = boCourier.Active,
                IsInDelivery = boCourier.IsInDelivery
            };
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }

    /// <summary>
    /// Retrieves the delivery history for a specific courier.
    /// </summary>
    /// <param name="courierId">The ID of the courier.</param>
    /// <returns>An IEnumerable of the courier's deliveries.</returns>
    public static IEnumerable<BO.DeliveryInList> GetCourierDeliveryHistory(int courierId)
    {
        // 1. Validate courier exists by reading from DAL.
        if (s_dal.Courier.Read(courierId) == null)
            throw new BO.BlDoesNotExistException($"Courier with ID {courierId} not found.");

        // 2. Fetch all DO.Delivery for the courier.
        var doDeliveries = s_dal.Delivery.ReadAll(d => d.CourierId == courierId);

        // 3. Fetch all unique DO.Order for these deliveries and put them in a dictionary for efficient lookup.
        // Using Method Syntax for the setup
        var orderIds = doDeliveries.Select(d => d.OrderId).Distinct();
        var doOrders = s_dal.Order.ReadAll(o => orderIds.Contains(o.Id)).ToDictionary(o => o.Id);
        
        var config = s_dal.Config;

        // 4. Create BO.DeliveryInList using Query Syntax (Demonstrates: Sorting, Select New, Let)
        return from d in doDeliveries
               let order = doOrders.GetValueOrDefault(d.OrderId)
               orderby d.DeliveryStartTime // Sorting
               select new BO.DeliveryInList // Projection
               {
                   Id = d.Id,
                   OrderId = d.OrderId,
                   CourierId = d.CourierId,
                   DeliveryStartTime = d.DeliveryStartTime,
                   ScheduleStatus = order != null ? Tools.DetermineScheduleStatus(order, config, d) : BO.ScheduleStatus.OnTime,
                   DeliveryEndType = d.DeliveryEndType.HasValue ? (BO.DeliveryEndTypes?)d.DeliveryEndType.Value : null,
                   DeliveryEndTime = d.DeliveryEndTime
               };
    }
    
    /// <summary>
    /// Retrieves all open orders that are within a courier's maximum delivery distance.
    /// </summary>
    /// <param name="courierId">The ID of the courier.</param>
    /// <returns>An IEnumerable of open orders available to the courier.</returns>
    public static IEnumerable<BO.OrderInList> GetOpenOrders(int courierId)
    {
        try
        {
            // The courier must exist to get available orders.
            DO.Courier doCourier = s_dal.Courier.Read(courierId)
                                   ?? throw new BO.BlDoesNotExistException($"Courier with ID {courierId} not found.");

            var allOrders = s_dal.Order.ReadAll();
            var allDeliveries = s_dal.Delivery.ReadAll();

            // Use Query Syntax (Demonstrates: Join Into, Let, Where, OrderBy)
            var openOrders =
                from order in allOrders
                join delivery in allDeliveries on order.Id equals delivery.OrderId into deliveries

                // Filter 1: Must not be currently in progress
                let inProgress = deliveries.Any(d => d.DeliveryEndTime == null)
                where !inProgress

                // Filter 2: If history exists, last status must be 're-openable'
                let lastEnded = deliveries.OrderByDescending(d => d.DeliveryEndTime).FirstOrDefault()
                where lastEnded == null ||
                      lastEnded.DeliveryEndType == DO.DeliveryEndTypes.RecipientNotFound ||
                      lastEnded.DeliveryEndType == DO.DeliveryEndTypes.Failed

                orderby order.OrderOpenTime // Sort by oldest first
                select new { order, deliveries };

            // Filter by the courier's personal delivery distance, if specified.
            var availableForCourier = openOrders; // Type is inferred
            if (doCourier.PersonalMaxDeliveryDistance != null)
            {
                var config = s_dal.Config;
                availableForCourier = openOrders.Where(x =>
                    Tools.GetAerialDistance(
                        (double)(config.Latitude ?? 0),
                        (double)(config.Longitude ?? 0),
                        x.order.Latitude,
                        x.order.Longitude) <= doCourier.PersonalMaxDeliveryDistance);
            }

            // Convert the final list of DOs to BOs, passing the already-fetched deliveries.
            return availableForCourier.Select(x => OrderManager.ConvertDoToBo(x.order, x.deliveries))
                                      .Select(OrderManager.ConvertBoToOrderInList);
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }

    /// <summary>
    /// Determines if an order is within a courier's maximum delivery range.
    /// </summary>
    /// <param name="order">The order to check.</param>
    /// <param name="courier">The courier.</param>
    /// <param name="hqLatitude">The latitude of the headquarters.</param>
    /// <param name="hqLongitude">The longitude of the headquarters.</param>
    /// <returns>True if the order is in range, false otherwise.</returns>
    internal static bool IsOrderInCourierRange(BO.Order order, BO.Courier courier, double hqLatitude, double hqLongitude)
    {
        if (!courier.PersonalMaxDeliveryDistance.HasValue)
        {
            return true;
        }
        var (lat, lon) = Tools.GetCoordinates(order.FullOrderAddress!);
        var distance = Tools.GetAerialDistance(hqLatitude, hqLongitude, lat, lon);
        return distance <= courier.PersonalMaxDeliveryDistance.Value;
    }

    /// <summary>
    /// Calculates and retrieves statistics for a specific courier.
    /// </summary>
    /// <param name="courierId">The ID of the courier.</param>
    /// <returns>A BO.CourierStatistics object.</returns>
    public static BO.CourierStatistics GetCourierStatistics(int courierId)
    {
        try
        {
            // 1. Validate courier exists
            if (s_dal.Courier.Read(courierId) == null)
                throw new BO.BlDoesNotExistException($"Courier with ID {courierId} not found.");

            // 2. Fetch all DO.Delivery for the courier once and materialize the list.
            var allCourierDeliveries = s_dal.Delivery.ReadAll(d => d.CourierId == courierId).ToList();

            // Handle case where courier has no deliveries at all.
            if (!allCourierDeliveries.Any())
            {
                return new BO.CourierStatistics();
            }

            // 3. Fetch associated orders for all deliveries.
            var orderIds = allCourierDeliveries.Select(d => d.OrderId).Distinct();
            var doOrders = s_dal.Order.ReadAll(o => orderIds.Contains(o.Id))
                                    .ToDictionary(o => o.Id);

            // 4. Filter for completed deliveries from the local list.
            var completedDoDeliveries = allCourierDeliveries.Where(d => d.DeliveryEndTime != null).ToList();

            // Handle case where there are deliveries, but none are completed yet.
            if (!completedDoDeliveries.Any())
            {
                // Still report the total number of deliveries assigned (which are all in-progress).
                return new BO.CourierStatistics { TotalDeliveries = allCourierDeliveries.Count };
            }

            // 5. Calculate all statistics directly from the DO collections.
            var config = s_dal.Config;
            var totalDeliveries = completedDoDeliveries.Count;

            var onTimeDeliveries = completedDoDeliveries.Count(d =>
                doOrders.TryGetValue(d.OrderId, out var order) &&
                Tools.DetermineScheduleStatus(order, config, d) == BO.ScheduleStatus.OnTime
            );

            // Demonstrate Grouping using Query Syntax
            var deliveryOutcomes = from d in completedDoDeliveries
                                   group d by d.DeliveryEndType into g
                                   select new { Status = g.Key, Count = g.Count() };

            var successfulDeliveries = deliveryOutcomes.FirstOrDefault(x => x.Status == DO.DeliveryEndTypes.Delivered)?.Count ?? 0;

            var deliveryDurations = completedDoDeliveries
                .Select(d => (d.DeliveryEndTime!.Value - d.DeliveryStartTime).TotalMinutes);

            return new BO.CourierStatistics
            {
                TotalDeliveries = totalDeliveries,
                TotalDistance = Math.Round(completedDoDeliveries.Sum(d => d.ActualDistance ?? 0), 2),
                AverageDeliveryTime = TimeSpan.FromMinutes(deliveryDurations.Any() ? deliveryDurations.Average() : 0),
                OnTimeDeliveries = onTimeDeliveries,
                LateDeliveries = totalDeliveries - onTimeDeliveries,
                SuccessRate = totalDeliveries > 0 ? Math.Round((double)successfulDeliveries / totalDeliveries * 100, 2) : 0
            };
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }


    /// <summary>
    /// Periodically checks all active couriers and deactivates those who have been 
    /// inactive longer than the allowed InactivityRange.
    /// </summary>
    public static void PeriodicCouriersUpdate(DateTime oldClock, DateTime newClock)
    {
        try
        {
            var config = s_dal.Config;
            var inactivityRange = config.InactivityRange; //

            // Use Query Syntax for the complex correlation logic (Demonstrates: Join Into, Let, Where, Select)
            var inactiveCouriersQuery =
                from c in s_dal.Courier.ReadAll(c => c.Active)
                join d in s_dal.Delivery.ReadAll() on c.Id equals d.CourierId into deliveries

                where !deliveries.Any(d => d.DeliveryEndTime == null) // Not currently busy

                let lastActivity = deliveries
                    .Select(d => d.DeliveryEndTime ?? DateTime.MinValue)
                    .DefaultIfEmpty(c.EmploymentStartTime)
                    .Max()
                where (newClock - lastActivity) > inactivityRange
                select new { Courier = c };

            // Materialize and update (required to avoid updating IEnumerable while iterating)
            var couriersToUpdate = inactiveCouriersQuery.ToList();
            if (couriersToUpdate.Any())
            {
                couriersToUpdate.ForEach(x =>
                {
                    Debug.WriteLine($"Deactivating courier ID {x.Courier.Id} due to inactivity.");
                    s_dal.Courier.Update(x.Courier with { Active = false });
                    Observers.NotifyItemUpdated(x.Courier.Id);
                });
                Observers.NotifyListUpdated();
            }
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }
}
