// Generated by gemini, prompt in readme under stage 4
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Helpers;

/// <summary>
/// Manager class for Order entity operations, providing conversion methods
/// between data layer (DO) and business layer (BO) representations.
/// </summary>
internal static class OrderManager
{
    private static DalApi.IDal s_dal = DalApi.Factory.Get;
    internal static ObserverManager Observers = new();

    /// <summary>
    /// Validates a business layer Order entity.
    /// </summary>
    /// <param name="boOrder">The BO Order to validate.</param>
    /// <param name="lat">The latitude of the order's address.</param>
    /// <param name="lon">The longitude of the order's address.</param>
    public static void OrderValidation(BO.Order boOrder, double? lat, double? lon)
    {
        var errors = new Dictionary<string, string>();
        try
        {
            if (boOrder == null)
                throw new BO.BlInvalidNullInputException("Order object cannot be null.");

            if (!Enum.IsDefined(typeof(BO.OrderTypes), boOrder.OrderType))
                errors[nameof(BO.Order.OrderType)] = "Invalid order type.";

            if (string.IsNullOrWhiteSpace(boOrder.VerbalDescription))
                errors[nameof(BO.Order.VerbalDescription)] = "Order verbal description cannot be empty.";
            else if (boOrder.VerbalDescription.Length > 255)
                errors[nameof(BO.Order.VerbalDescription)] = "Order verbal description is too long.";
            
            var nameError = Tools.ValidateFullName(boOrder.CustomerFullName, "Customer full name");
            if (nameError != null) errors[nameof(BO.Order.CustomerFullName)] = nameError;

            var phoneError = Tools.ValidatePhoneNumber(boOrder.CustomerMobile, "Customer mobile");
            if (phoneError != null) errors[nameof(BO.Order.CustomerMobile)] = phoneError;

            if (boOrder.Volume <= 0)
                errors[nameof(BO.Order.Volume)] = $"Volume {boOrder.Volume} must be positive.";
            else if (boOrder.Volume > 100000)
                errors[nameof(BO.Order.Volume)] = $"Volume {boOrder.Volume} is too large.";

            if (boOrder.Weight <= 0)
                errors[nameof(BO.Order.Weight)] = $"Weight {boOrder.Weight} must be positive.";
            else if (boOrder.Weight > 10000)
                errors[nameof(BO.Order.Weight)] = $"Weight {boOrder.Weight} is too large.";

            if (boOrder.Height <= 0)
                errors[nameof(BO.Order.Height)] = $"Height {boOrder.Height} must be positive.";
            else if (boOrder.Height > 5000)
                errors[nameof(BO.Order.Height)] = $"Height {boOrder.Height} is too large.";

            if (boOrder.Width <= 0)
                errors[nameof(BO.Order.Width)] = $"Width {boOrder.Width} must be positive.";
            else if (boOrder.Width > 5000)
                errors[nameof(BO.Order.Width)] = $"Width {boOrder.Width} is too large.";

            if (boOrder.FullOrderAddress != null && boOrder.FullOrderAddress.Length > 255)
                errors[nameof(BO.Order.FullOrderAddress)] = "Order address is too long.";
            else if (string.IsNullOrWhiteSpace(boOrder.FullOrderAddress))
                errors[nameof(BO.Order.FullOrderAddress)] = "Order address cannot be empty.";
            else if (lat == null || lon == null)
                errors[nameof(BO.Order.FullOrderAddress)] = "Order address is invalid or not found.";
            else
            {
                var config = s_dal.Config;
                var distance = Tools.GetAerialDistance((double)(config.Latitude ?? 0), (double)(config.Longitude ?? 0), lat.Value, lon.Value);
                if (config.MaxGeneralDeliveryDistanceKm.HasValue && distance > config.MaxGeneralDeliveryDistanceKm)
                    errors[nameof(BO.Order.FullOrderAddress)] = $"Order location is too far from the company's location. a maximum of {config.MaxGeneralDeliveryDistanceKm}km is allowed";
            }

            if (errors.Any())
                throw new BO.BlInvalidInputException(string.Join(Environment.NewLine, errors.Values)) { ValidationErrors = errors };
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }

    /// <summary>
    /// Converts a business layer Order entity to its data layer equivalent.
    /// </summary>
    /// <param name="boOrder">The BO Order to convert.</param>
    /// <returns>An equivalent DO Order entity.</returns>
    /// <exception cref="BO.BlInvalidInputException">Thrown when conversion fails.</exception>
    public static DO.Order ConvertBoToDo(BO.Order boOrder, double? lat = null, double? lon = null)
    {
        // Round doubles to two decimal points
        boOrder.Volume = Math.Round(boOrder.Volume, 2);
        boOrder.Weight = Math.Round(boOrder.Weight, 2);
        boOrder.Height = Math.Round(boOrder.Height, 2);
        boOrder.Width = Math.Round(boOrder.Width, 2);

        if (lat == null || lon == null)
        {
            try
            {
                (lat, lon) = Tools.GetCoordinates(boOrder.FullOrderAddress!);
            }
            catch { /* Ignore, OrderValidation will catch */ }
        }
        OrderValidation(boOrder, lat, lon);
        try
        {
            return new DO.Order(
                Id: boOrder.Id,
                OrderType: (DO.OrderTypes)boOrder.OrderType,
                VerbalDescription: boOrder.VerbalDescription,
                Latitude: lat ?? 0,
                Longitude: lon ?? 0,
                CustomerFullName: boOrder.CustomerFullName,
                CustomerMobile: boOrder.CustomerMobile,
                Volume: boOrder.Volume,
                Weight: boOrder.Weight,
                Fragile: boOrder.Fragile,
                Height: boOrder.Height,
                Width: boOrder.Width,
                OrderOpenTime: boOrder.OrderOpenTime,
                FullOrderAddress: boOrder.FullOrderAddress
            );
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }

    /// <summary>
    /// Converts a data layer Order entity to its business layer equivalent.
    /// </summary>
    /// <param name="doOrder">The DO Order to convert.</param>
    /// <returns>An equivalent BO Order entity.</returns>
    /// <exception cref="BO.BlInvalidInputException">Thrown when conversion fails.</exception>
    public static BO.Order ConvertDoToBo(DO.Order doOrder)
    {
        var deliveries = s_dal.Delivery.ReadAll(d => d.OrderId == doOrder.Id);
        return ConvertDoToBo(doOrder, deliveries);
    }

    /// <summary>
    /// Converts a data layer Order entity to its business layer equivalent, using pre-fetched deliveries.
    /// </summary>
    /// <param name="doOrder">The DO Order to convert.</param>
    /// <param name="deliveries">The pre-fetched deliveries for the order.</param>
    /// <returns>An equivalent BO Order entity.</returns>
    internal static BO.Order ConvertDoToBo(DO.Order doOrder, IEnumerable<DO.Delivery> deliveries)
    {
        try
        {
            var boOrder = new BO.Order
            {
                Id = doOrder.Id,
                OrderType = (BO.OrderTypes)doOrder.OrderType,
                VerbalDescription = doOrder.VerbalDescription,
                CustomerFullName = doOrder.CustomerFullName,
                CustomerMobile = doOrder.CustomerMobile,
                Volume = doOrder.Volume,
                Weight = doOrder.Weight,
                Fragile = doOrder.Fragile,
                Height = doOrder.Height,
                Width = doOrder.Width,
                OrderOpenTime = doOrder.OrderOpenTime,
                FullOrderAddress = doOrder.FullOrderAddress,
                TimeOpenedDuration = AdminManager.Now - doOrder.OrderOpenTime,
            };
            
            boOrder.OrderStatus = DetermineOrderStatus(deliveries);

            DO.Delivery? lastDelivery = null;
            if (deliveries.Any())
                lastDelivery = deliveries.OrderByDescending(d => d.DeliveryStartTime).FirstOrDefault();
            var config = s_dal.Config;
            //if open, calculate based on open time
            if (boOrder.OrderStatus == BO.OrderStatus.Open)
            {
                boOrder.ScheduleStatus = Tools.DetermineScheduleStatus(doOrder, config);                
            }
            // if closed/inprogress calculate based on last/current delivery
            else
            {
                boOrder.ScheduleStatus = Tools.DetermineScheduleStatus(doOrder, config, lastDelivery);
            }

            return boOrder;
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }



    /// <summary>
    /// Determines the status of an order based on its delivery history.
    /// </summary>
    /// <param name="deliveries">The list of deliveries associated with the order.</param>
    /// <returns>The calculated order status.</returns>
    internal static BO.OrderStatus DetermineOrderStatus(IEnumerable<DO.Delivery> deliveries)
    {
        if (!deliveries.Any())
        {
            return BO.OrderStatus.Open;
        }

        if (deliveries.Any(d => d.DeliveryEndTime == null))
        {
            return BO.OrderStatus.InProgress;
        }

        var lastEnded = deliveries.OrderByDescending(d => d.DeliveryEndTime).First();
        return lastEnded.DeliveryEndType switch
        {
            DO.DeliveryEndTypes.Delivered => BO.OrderStatus.Delivered,
            DO.DeliveryEndTypes.CustomerRefused => BO.OrderStatus.Refused,
            DO.DeliveryEndTypes.Cancelled => BO.OrderStatus.Cancelled,
            DO.DeliveryEndTypes.RecipientNotFound => BO.OrderStatus.Open,
            DO.DeliveryEndTypes.Failed => BO.OrderStatus.Open,
            _ => throw new BO.BlMissingPropertyException("Unrecognized delivery end type. Can't determine order status"),
        };
    }

    /// <summary>
    /// Converts a business layer Order entity to a summary list view.
    /// Summary entities are derived from full BO entities (not directly from DO)
    /// to ensure calculated properties and validations are preserved.
    /// </summary>
    /// <param name="boOrder">The BO Order to convert.</param>
    /// <returns>An OrderInList summary entity.</returns>
    /// <exception cref="BO.BlInvalidInputException">Thrown when conversion fails.</exception>
    public static BO.OrderInList ConvertBoToOrderInList(BO.Order boOrder)
    {
        try
        {
            return new BO.OrderInList
            {
                Id = boOrder.Id,
                OrderType = boOrder.OrderType,
                CustomerFullName = boOrder.CustomerFullName,
                OrderStatus = boOrder.OrderStatus,
                OrderOpenTime = boOrder.OrderOpenTime,
                ScheduleStatus = boOrder.ScheduleStatus
            };
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }
    
    /// <summary>
    /// Retrieves all orders from the data layer and converts them to a list of BO Orders.
    /// </summary>
    /// <param name="filter">An optional filter to apply to the orders.</param>
    /// <returns>An IEnumerable of BO.Order.</returns>
    public static IEnumerable<BO.Order> ReadAll(Func<DO.Order, bool>? filter = null)
    {
        try
        {
            return s_dal.Order.ReadAll(filter).Where(o => o != null).Select(o => ConvertDoToBo(o!));
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }

    /// <summary>
    /// Retrieves a single order by its ID.
    /// </summary>
    /// <param name="orderId">The ID of the order to retrieve.</param>
    /// <returns>A BO.Order object.</returns>
    public static BO.Order Read(int orderId)
    {
        DO.Order? doOrder = s_dal.Order.Read(orderId);
        if (doOrder == null)
        {
            throw new BO.BlDoesNotExistException($"Order with ID {orderId} not found.");
        }
        try
        {
            return ConvertDoToBo(doOrder);
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }

    /// <summary>
    /// Creates a new order.
    /// </summary>
    /// <param name="newOrder">The BO.Order object for the new order.</param>
    public static void Create(BO.Order newOrder)
    {
        
        if (s_dal.Config.CompanyFullAddress == null)
            throw new BO.BlOrderNotDeliverableException("Orders can't be opened when the company HQ address is null");
        try
        {
            s_dal.Order.Create(ConvertBoToDo(newOrder));
            Observers.NotifyListUpdated();
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }
    
    public static void Update(BO.Order updatedOrder)
    {
        if (updatedOrder == null)
            throw new BO.BlInvalidNullInputException("Order object cannot be null.");

        try
        {
            // Verify that the order does not have a delivery in progress - OPTIMIZED
            if (s_dal.Delivery.ReadAll(d => d.OrderId == updatedOrder.Id && d.DeliveryEndTime == null).Any())
                throw new BO.BlDeliveryInProgressException(
                    $"Order ID '{updatedOrder.Id}' cannot be updated as it is currently being delivered.");

            // Verify that the order is not finalized (Delivered or Cancelled)
            var deliveries = s_dal.Delivery.ReadAll(d => d.OrderId == updatedOrder.Id);
            var status = DetermineOrderStatus(deliveries);
            if (status == BO.OrderStatus.Delivered || status == BO.OrderStatus.Cancelled || status == BO.OrderStatus.Refused)
                throw new BO.BlDeliveryAlreadyClosedException($"Order {updatedOrder.Id} cannot be updated because it is {status}.");
            
            // Read the original order from DAL to preserve immutable properties
            DO.Order? originalOrder = s_dal.Order.Read(updatedOrder.Id);
            if (originalOrder == null)
                throw new BO.BlDoesNotExistException($"Order with ID {updatedOrder.Id} not found.");

            if (originalOrder.OrderOpenTime != updatedOrder.OrderOpenTime)
                throw new BO.BlInvalidInputException("OrderOpenTime cannot be modified");

            double? lat = null, lon = null;
            if (originalOrder.FullOrderAddress == updatedOrder.FullOrderAddress)
            {
                lat = originalOrder.Latitude;
                lon = originalOrder.Longitude;
            }
            
            s_dal.Order.Update(ConvertBoToDo(updatedOrder, lat, lon));
            Observers.NotifyItemUpdated(updatedOrder.Id);
            Observers.NotifyListUpdated();
        }
        catch (Exception ex)
        {
                throw Tools.ConvertDalException(ex);
        }
    }
    
    /// <summary>
    /// Deletes an order by its ID.
    /// </summary>
    /// <param name="orderId">The ID of the order to delete.</param>
    public static void Delete(int orderId)
    {
        try
        {
            // Verify that the order has not been assigned to a courier - OPTIMIZED
            if (s_dal.Delivery.ReadAll(d => d.OrderId == orderId && d.DeliveryEndTime == null).Any())
                throw new BO.BlOrderAlreadyAssignedException(
                    $"Order ID '{orderId}' cannot be deleted as it is already assigned to a courier.");
            s_dal.Order.Delete(orderId);
            Observers.NotifyListUpdated();
            Observers.NotifyItemUpdated(orderId);
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }
    
    /// <summary>
    /// gets the tracking information for an order
    /// </summary>
    /// <param name="orderId">the id of the order to get the tracking information for</param>
    /// <returns>the tracking information for the order</returns>
    public static BO.OrderTracking GetOrderTracking(int orderId)
    {
        try
        {
            DO.Order doOrder = s_dal.Order.Read(orderId) ??
                throw new BO.BlDoesNotExistException($"Order with ID {orderId} does not exist");

            var deliveries = s_dal.Delivery.ReadAll(d => d.OrderId == orderId);
            BO.OrderStatus status = DetermineOrderStatus(deliveries);
            DO.Delivery? activeDelivery = deliveries.FirstOrDefault(d => d != null && d.DeliveryEndTime == null);

            // Get config once at the top
            var config = s_dal.Config;

            // Get Assigned Courier (only if InProgress) - OPTIMIZED
            BO.CourierInList? assignedCourier = null;
            if (status == BO.OrderStatus.InProgress && activeDelivery != null)
            {
                try
                {
                    var doCourier = s_dal.Courier.Read(activeDelivery.CourierId);
                    if (doCourier != null)
                    {
                        assignedCourier = new BO.CourierInList
                        {
                            Id = doCourier.Id,
                            FullName = doCourier.FullName,
                            DeliveryType = (BO.DeliveryTypes)doCourier.DeliveryType,
                            Active = doCourier.Active
                        };
                    }
                }
                catch (DO.DalDoesNotExistException) { /* Courier might have been deleted, ignore */ }
            }

            IEnumerable<BO.DeliveryInList> history = Enumerable.Empty<BO.DeliveryInList>();

            // Map Delivery History if exists
            if (deliveries.Any())
            {
                history = deliveries
                    .OrderByDescending(d => d.DeliveryStartTime)
                    .Select(d => new BO.DeliveryInList
                    {
                        Id = d.Id,
                        OrderId = d.OrderId,
                        CourierId = d.CourierId,
                        DeliveryStartTime = d.DeliveryStartTime,
                        ScheduleStatus = Tools.DetermineScheduleStatus(doOrder, config, d), // Pass config
                        DeliveryEndType = d.DeliveryEndType.HasValue ? (BO.DeliveryEndTypes?)d.DeliveryEndType.Value : null,
                        DeliveryEndTime = d.DeliveryEndTime
                    });
            }

                // Calculate Timing Properties - FIXED
            DateTime? maxDeliveryTime = doOrder.OrderOpenTime.Add(config.MaxDeliveryTimeSpan);
            DateTime? expectedDeliveryTime = null;

            expectedDeliveryTime = Tools.CalculateExpectedDeliveryTime(activeDelivery.DeliveryType, doOrder, config, activeDelivery); // Pass config

            return new BO.OrderTracking
            {
                Id = doOrder.Id,
                Status = status,
                AssignedCourier = assignedCourier,
                DeliveryHistory = history,
                VerbalDescription = doOrder.VerbalDescription,
                CustomerFullName = doOrder.CustomerFullName,
                OrderOpenTime = doOrder.OrderOpenTime,
                ExpectedDeliveryTime = expectedDeliveryTime,
                MaxDeliveryTime = maxDeliveryTime,
                FullOrderAddress = doOrder.FullOrderAddress
            };
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }


    /// <summary>
    /// a method for periodic updates of the order
    /// </summary>
    /// <param name="oldClock"></param>
    /// <param name="newClock"></param>
    public static void PeriodicOrdersUpdate(DateTime oldClock, DateTime newClock)
    {
        //implementation will be added in the future
    }

    /// <summary>
    /// Cancels an order.
    /// </summary>
    /// <param name="orderId">The ID of the order to cancel.</param>
    public static void Cancel(int orderId)
    {
        try
        {
            BO.Order order = Read(orderId);

            switch (order.OrderStatus)
            {
                case BO.OrderStatus.InProgress:
                    // Find the active delivery
                    var activeDelivery = s_dal.Delivery.Read(d => d.OrderId == orderId && d.DeliveryEndTime == null);
                    if (activeDelivery != null)
                    {
                        // Cancel the delivery
                        activeDelivery = activeDelivery with
                        {
                            DeliveryEndTime = AdminManager.Now,
                            DeliveryEndType = DO.DeliveryEndTypes.Cancelled
                        };
                        s_dal.Delivery.Update(activeDelivery);
                    }
                    break;

                case BO.OrderStatus.Open:
                    // Create a dummy delivery
                    DeliveryManager.CreateCancelledDelivery(orderId);
                    break;

                case BO.OrderStatus.Delivered:
                case BO.OrderStatus.Cancelled:
                case BO.OrderStatus.Refused:
                    throw new BO.BlOrderCannotBeCancelledException(
                        $"Order ID '{orderId}' cannot be cancelled as it is already in status {order.OrderStatus}.");
            }
            Observers.NotifyItemUpdated(orderId);
            Observers.NotifyListUpdated();
        }
        catch (Exception ex)
        {
            throw Tools.ConvertDalException(ex);
        }
    }
}
