// Generated by Gemini. Prompt is in the Readme under Stage 5
using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Input;

namespace PL.Delivery;

/// <summary>
/// Interaction logic for DeliveryAssignmentWindow.xaml
/// </summary>
public partial class DeliveryAssignmentWindow : Window
{
    private static readonly BlApi.IBl s_bl = BlApi.Factory.Get();
    private int _selectedCourierId;

    // Text displayed at the top of the window, changes based on step
    public string Legend
    {
        get { return (string)GetValue(LegendProperty); }
        set { SetValue(LegendProperty, value); }
    }
    public static readonly DependencyProperty LegendProperty =
        DependencyProperty.Register("Legend", typeof(string), typeof(DeliveryAssignmentWindow), new PropertyMetadata(string.Empty));

    public IEnumerable<BO.CourierInList> CourierList
    {
        get { return (IEnumerable<BO.CourierInList>)GetValue(CourierListProperty); }
        set { SetValue(CourierListProperty, value); }
    }
    public static readonly DependencyProperty CourierListProperty =
        DependencyProperty.Register("CourierList", typeof(IEnumerable<BO.CourierInList>), typeof(DeliveryAssignmentWindow), new PropertyMetadata(null));

    public IEnumerable<BO.OrderInList> OrderList
    {
        get { return (IEnumerable<BO.OrderInList>)GetValue(OrderListProperty); }
        set { SetValue(OrderListProperty, value); }
    }
    public static readonly DependencyProperty OrderListProperty =
        DependencyProperty.Register("OrderList", typeof(IEnumerable<BO.OrderInList>), typeof(DeliveryAssignmentWindow), new PropertyMetadata(null));

    // Controls which DataGrid is visible. Toggled in logic.
    public Visibility CourierListVisibility
    {
        get { return (Visibility)GetValue(CourierListVisibilityProperty); }
        set { SetValue(CourierListVisibilityProperty, value); }
    }
    public static readonly DependencyProperty CourierListVisibilityProperty =
        DependencyProperty.Register("CourierListVisibility", typeof(Visibility), typeof(DeliveryAssignmentWindow), new PropertyMetadata(Visibility.Visible));

    public Visibility OrderListVisibility
    {
        get { return (Visibility)GetValue(OrderListVisibilityProperty); }
        set { SetValue(OrderListVisibilityProperty, value); }
    }
    public static readonly DependencyProperty OrderListVisibilityProperty =
        DependencyProperty.Register("OrderListVisibility", typeof(Visibility), typeof(DeliveryAssignmentWindow), new PropertyMetadata(Visibility.Collapsed));

    public BO.CourierInList? SelectedCourier
    {
        get { return (BO.CourierInList?)GetValue(SelectedCourierProperty); }
        set { SetValue(SelectedCourierProperty, value); }
    }
    public static readonly DependencyProperty SelectedCourierProperty =
        DependencyProperty.Register("SelectedCourier", typeof(BO.CourierInList), typeof(DeliveryAssignmentWindow), new PropertyMetadata(null));

    public BO.OrderInList? SelectedOrder
    {
        get { return (BO.OrderInList?)GetValue(SelectedOrderProperty); }
        set { SetValue(SelectedOrderProperty, value); }
    }
    public static readonly DependencyProperty SelectedOrderProperty =
        DependencyProperty.Register("SelectedOrder", typeof(BO.OrderInList), typeof(DeliveryAssignmentWindow), new PropertyMetadata(null));

    public DeliveryAssignmentWindow()
    {
        InitializeComponent();
        LoadCouriers();
        Loaded += (s, e) => 
        {
            s_bl.Admin.AddClockObserver(Observer);
            s_bl.Courier.AddObserver(Observer);
            s_bl.Order.AddObserver(Observer);
        };
        Closing += (s, e) => 
        {
            s_bl.Admin.RemoveClockObserver(Observer);
            s_bl.Courier.RemoveObserver(Observer);
            s_bl.Order.RemoveObserver(Observer);
        };
    }

    /// <summary>
    /// Loads the list of active couriers who are not currently in a delivery.
    /// </summary>
    private void LoadCouriers()
    {
        Legend = "Choose courier to assign";
        CourierList = s_bl.Courier.ReadAll(c => c.Active && !s_bl.Courier.IsCourierInDelivery(c.Id));
        CourierListVisibility = Visibility.Visible;
        OrderListVisibility = Visibility.Collapsed;
    }

    /// <summary>
    /// Handles double-click on a courier to select them and show available orders.
    /// </summary>
    private void Courier_MouseDoubleClick(object sender, MouseButtonEventArgs e)
    {
        if (SelectedCourier == null) return;

        _selectedCourierId = SelectedCourier.Id;
        // Switch view: Hide couriers, show orders available for this courier
        Legend = "Choose order to assign";
        
        try 
        {
            OrderList = s_bl.Courier.GetOpenOrders(_selectedCourierId);
            CourierListVisibility = Visibility.Collapsed;
            OrderListVisibility = Visibility.Visible;
        }
        catch (System.Exception ex)
        {
             MessageBox.Show(this, ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Handles double-click on an order to assign it to the selected courier.
    /// </summary>
    private void Order_MouseDoubleClick(object sender, MouseButtonEventArgs e)
    {
        if (SelectedOrder == null) return;

        try
        {
            // Perform the assignment in BL
            s_bl.Delivery.PickUp(_selectedCourierId, SelectedOrder.Id);
            MessageBox.Show(this, "Delivery Assigned", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
            Close();
        }
        catch (System.Exception ex)
        {
            MessageBox.Show(this, ex.Message, "Error", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    /// <summary>
    /// Observer to refresh lists when the clock updates.
    /// </summary>
    private void Observer()
    {
        Dispatcher.Invoke(() =>
        {
            if (CourierListVisibility == Visibility.Visible)
                // If viewing couriers, refresh courier list
                LoadCouriers();
            else if (OrderListVisibility == Visibility.Visible)
            {
                try
                {
                    OrderList = s_bl.Courier.GetOpenOrders(_selectedCourierId);
                }
                catch { LoadCouriers(); }
            }
        });
    }
}