﻿﻿﻿﻿// Generated by Gemini. Prompt is in the Readme under Stage 5
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace PL.Delivery;

    /// <summary>
    /// Interaction logic for DeliveryInListWindow.xaml
    /// </summary>
    public partial class DeliveryListWindow : Window
    {
        // Access to the Business Layer
        static readonly BlApi.IBl s_bl = BlApi.Factory.Get();

        public object StatusFilter
        {
            get { return (object)GetValue(StatusFilterProperty); }
            set { SetValue(StatusFilterProperty, value); }
        }
        public static readonly DependencyProperty StatusFilterProperty =
            DependencyProperty.Register("StatusFilter", typeof(object), typeof(DeliveryListWindow), new PropertyMetadata("None"));

        public object EndTypeFilter
        {
            get { return (object)GetValue(EndTypeFilterProperty); }
            set { SetValue(EndTypeFilterProperty, value); }
        }
        public static readonly DependencyProperty EndTypeFilterProperty =
            DependencyProperty.Register("EndTypeFilter", typeof(object), typeof(DeliveryListWindow), new PropertyMetadata("None"));

        // Dependency Property for the list of deliveries
        public IEnumerable<BO.DeliveryInList> DeliveryList
        {
            get { return (IEnumerable<BO.DeliveryInList>)GetValue(DeliveryListProperty); }
            set { SetValue(DeliveryListProperty, value); }
        }

        public static readonly DependencyProperty DeliveryListProperty =
            DependencyProperty.Register("DeliveryList", typeof(IEnumerable<BO.DeliveryInList>), typeof(DeliveryListWindow), new PropertyMetadata(null));

        // Currently selected delivery
        public BO.DeliveryInList? SelectedDelivery
        {
            get { return (BO.DeliveryInList?)GetValue(SelectedDeliveryProperty); }
            set { SetValue(SelectedDeliveryProperty, value); }
        }

        public static readonly DependencyProperty SelectedDeliveryProperty =
            DependencyProperty.Register("SelectedDelivery", typeof(BO.DeliveryInList), typeof(DeliveryListWindow), new PropertyMetadata(null));

        public ICommand CancelSingleCommand { get; }

        public DeliveryListWindow()
        {
            InitializeComponent();
            CancelSingleCommand = new RelayCommand(CancelSingleDelivery);
        }

        /// <summary>
        /// Refreshes the list applying both Status and EndType filters.
        /// </summary>
        private void RefreshList()
        {
            var deliveries = s_bl.Delivery.ReadAll();

            if (StatusFilter is BO.ScheduleStatus status)
                deliveries = deliveries.Where(d => d.ScheduleStatus == status);

            if (EndTypeFilter is BO.DeliveryEndTypes endType)
                deliveries = deliveries.Where(d => d.DeliveryEndType == endType);

            DeliveryList = deliveries;
        }

        /// <summary>
        /// Event handler for filter changes.
        /// </summary>
        private void cbFilter_SelectionChanged(object sender, SelectionChangedEventArgs e) => RefreshList();

        /// <summary>
        /// Observer setup to keep the list updated.
        /// </summary>
        private void deliveryListObserver() => Dispatcher.Invoke(RefreshList);

        /// <summary>
        /// Registers the observer when the window is loaded.
        /// </summary>
        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            s_bl.Delivery.AddObserver(deliveryListObserver);
            s_bl.Order.AddObserver(deliveryListObserver);
        }

        /// <summary>
        /// Unregisters the observer when the window is closed.
        /// </summary>
        private void Window_Closed(object sender, EventArgs e)
        {
            s_bl.Delivery.RemoveObserver(deliveryListObserver);
            s_bl.Order.RemoveObserver(deliveryListObserver);
        }

        /// <summary>
        /// Opens DeliveryWindow in Update mode.
        /// </summary>
        private void DataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            if (SelectedDelivery != null)
                new DeliveryWindow(SelectedDelivery.Id).Show();
        }

        /// <summary>
        /// Opens DeliveryWindow in Add mode.
        /// </summary>
        private void BtnAdd_Click(object sender, RoutedEventArgs e)
        {
            new DeliveryAssignmentWindow().Show();
        }

        /// <summary>
        /// Cancels a specific delivery (via Order cancellation logic) after confirmation.
        /// </summary>
        /// <param name="parameter">The DeliveryInList object to cancel.</param>
        private void CancelSingleDelivery(object parameter)
        {
            if (parameter is BO.DeliveryInList delivery)
            {
                if (MessageBox.Show($"Are you sure you want to cancel delivery {delivery.Id}?", "Cancel Confirmation", MessageBoxButton.YesNo, MessageBoxImage.Warning) == MessageBoxResult.Yes)
                {
                    try
                    {
                        s_bl.Order.Cancel(delivery.OrderId);
                    }
                    catch (Exception ex)
                    {
                        MessageBox.Show(ex.Message, "Cancellation Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    }
                }
            }
        }
    }

    /// <summary>
    /// A basic implementation of ICommand to handle commands from the UI.
    /// </summary>
    public class RelayCommand : ICommand
    {
        private readonly Action<object> _execute;
        private readonly Predicate<object>? _canExecute;

        public RelayCommand(Action<object> execute, Predicate<object>? canExecute = null)
        {
            _execute = execute;
            _canExecute = canExecute;
        }

        public bool CanExecute(object? parameter) => _canExecute == null || _canExecute(parameter!);
        public void Execute(object? parameter) => _execute(parameter!);
        public event EventHandler? CanExecuteChanged
        {
            add { CommandManager.RequerySuggested += value; }
            remove { CommandManager.RequerySuggested -= value; }
        }
    }
